-- Cặp từ phân biệt âm cho công cụ T8 (nghe chọn từ).
--
-- Dữ liệu dựng bởi scripts/build-minimal-pairs.mjs: cặp viết tay từ tài liệu
-- ESL rồi kiểm chứng máy với cmu-ipa.json (đúng một âm vị khác nhau). Không đào
-- từ điển ra vì cmudict ~40% là tên riêng. Migration này sinh bởi
-- scripts/gen-phonetic-pairs-seed.mjs.
--
-- Nội dung dùng chung, không có user_id.

CREATE TABLE IF NOT EXISTS phonetic_pairs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  contrast TEXT NOT NULL,         -- vd 'ɪ_iː'
  contrast_label TEXT NOT NULL,   -- vd '/ɪ/ – /iː/', hiện trên UI
  kind TEXT NOT NULL,
  word_a TEXT NOT NULL,
  word_b TEXT NOT NULL,
  ipa_a TEXT,
  ipa_b TEXT,
  UNIQUE (contrast, word_a, word_b)
);

CREATE INDEX IF NOT EXISTS idx_phonetic_pairs_contrast ON phonetic_pairs(contrast);

INSERT INTO phonetic_pairs (contrast, contrast_label, kind, word_a, word_b, ipa_a, ipa_b) VALUES
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'ship', 'sheep', '/ˈʃɪp/', '/ˈʃiːp/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'bit', 'beat', '/ˈbɪt/', '/ˈbiːt/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'sit', 'seat', '/ˈsɪt/', '/ˈsiːt/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'fit', 'feet', '/ˈfɪt/', '/ˈfiːt/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'fill', 'feel', '/ˈfɪl/', '/ˈfiːl/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'hill', 'heel', '/ˈhɪl/', '/ˈhiːl/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'still', 'steel', '/ˈstɪl/', '/ˈstiːl/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'list', 'least', '/ˈlɪst/', '/ˈliːst/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'itch', 'each', '/ˈɪtʃ/', '/ˈiːtʃ/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'chip', 'cheap', '/ˈtʃɪp/', '/ˈtʃiːp/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'dip', 'deep', '/ˈdɪp/', '/ˈdiːp/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'slip', 'sleep', '/ˈslɪp/', '/ˈsliːp/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'lip', 'leap', '/ˈlɪp/', '/ˈliːp/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'grin', 'green', '/ˈɡrɪn/', '/ˈɡriːn/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'bin', 'bean', '/ˈbɪn/', '/ˈbiːn/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'tin', 'teen', '/ˈtɪn/', '/ˈtiːn/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'hit', 'heat', '/ˈhɪt/', '/ˈhiːt/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'knit', 'neat', '/ˈnɪt/', '/ˈniːt/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'pitch', 'peach', '/ˈpɪtʃ/', '/ˈpiːtʃ/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'rich', 'reach', '/ˈrɪtʃ/', '/ˈriːtʃ/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'bid', 'bead', '/ˈbɪd/', '/ˈbiːd/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'hid', 'heed', '/ˈhɪd/', '/ˈhiːd/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'is', 'ease', '/ˈɪz/', '/ˈiːz/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'it', 'eat', '/ˈɪt/', '/ˈiːt/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'ill', 'eel', '/ˈɪl/', '/ˈiːl/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'fist', 'feast', '/ˈfɪst/', '/ˈfiːst/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'pick', 'peak', '/ˈpɪk/', '/ˈpiːk/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'lick', 'leak', '/ˈlɪk/', '/ˈliːk/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'sick', 'seek', '/ˈsɪk/', '/ˈsiːk/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'pill', 'peel', '/ˈpɪl/', '/ˈpiːl/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'mill', 'meal', '/ˈmɪl/', '/ˈmiːl/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'chick', 'cheek', '/ˈtʃɪk/', '/ˈtʃiːk/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'din', 'dean', '/ˈdɪn/', '/ˈdiːn/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'will', 'wheel', '/ˈwɪl/', '/ˈwiːl/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'bitten', 'beaten', '/ˈbɪtən/', '/ˈbiːtən/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'dim', 'deem', '/ˈdɪm/', '/ˈdiːm/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'sin', 'scene', '/ˈsɪn/', '/ˈsiːn/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'slit', 'sleet', '/ˈslɪt/', '/ˈsliːt/'),
  ('ɪ_iː', '/ɪ/ – /iː/', 'vowel', 'whip', 'weep', '/ˈwɪp/', '/ˈwiːp/'),
  ('æ_e', '/æ/ – /e/', 'vowel', 'bad', 'bed', '/ˈbæd/', '/ˈbɛd/'),
  ('æ_e', '/æ/ – /e/', 'vowel', 'bat', 'bet', '/ˈbæt/', '/ˈbɛt/'),
  ('æ_e', '/æ/ – /e/', 'vowel', 'sad', 'said', '/ˈsæd/', '/ˈsɛd/'),
  ('æ_e', '/æ/ – /e/', 'vowel', 'man', 'men', '/ˈmæn/', '/ˈmɛn/'),
  ('æ_e', '/æ/ – /e/', 'vowel', 'pan', 'pen', '/ˈpæn/', '/ˈpɛn/'),
  ('æ_e', '/æ/ – /e/', 'vowel', 'had', 'head', '/ˈhæd/', '/ˈhɛd/'),
  ('æ_e', '/æ/ – /e/', 'vowel', 'mat', 'met', '/ˈmæt/', '/ˈmɛt/'),
  ('æ_e', '/æ/ – /e/', 'vowel', 'sat', 'set', '/ˈsæt/', '/ˈsɛt/'),
  ('æ_e', '/æ/ – /e/', 'vowel', 'land', 'lend', '/ˈlænd/', '/ˈlɛnd/'),
  ('æ_e', '/æ/ – /e/', 'vowel', 'band', 'bend', '/ˈbænd/', '/ˈbɛnd/'),
  ('æ_e', '/æ/ – /e/', 'vowel', 'sand', 'send', '/ˈsænd/', '/ˈsɛnd/'),
  ('æ_e', '/æ/ – /e/', 'vowel', 'gas', 'guess', '/ˈɡæs/', '/ˈɡɛs/'),
  ('æ_e', '/æ/ – /e/', 'vowel', 'dad', 'dead', '/ˈdæd/', '/ˈdɛd/'),
  ('æ_e', '/æ/ – /e/', 'vowel', 'tan', 'ten', '/ˈtæn/', '/ˈtɛn/'),
  ('æ_e', '/æ/ – /e/', 'vowel', 'pat', 'pet', '/ˈpæt/', '/ˈpɛt/'),
  ('æ_e', '/æ/ – /e/', 'vowel', 'bag', 'beg', '/ˈbæɡ/', '/ˈbɛɡ/'),
  ('æ_e', '/æ/ – /e/', 'vowel', 'flash', 'flesh', '/ˈflæʃ/', '/ˈflɛʃ/'),
  ('æ_e', '/æ/ – /e/', 'vowel', 'jam', 'gem', '/ˈdʒæm/', '/ˈdʒɛm/'),
  ('æ_e', '/æ/ – /e/', 'vowel', 'lag', 'leg', '/ˈlæɡ/', '/ˈlɛɡ/'),
  ('æ_e', '/æ/ – /e/', 'vowel', 'mass', 'mess', '/ˈmæs/', '/ˈmɛs/'),
  ('æ_e', '/æ/ – /e/', 'vowel', 'past', 'pest', '/ˈpæst/', '/ˈpɛst/'),
  ('æ_e', '/æ/ – /e/', 'vowel', 'rack', 'wreck', '/ˈræk/', '/ˈrɛk/'),
  ('æ_e', '/æ/ – /e/', 'vowel', 'track', 'trek', '/ˈtræk/', '/ˈtrɛk/'),
  ('æ_e', '/æ/ – /e/', 'vowel', 'pack', 'peck', '/ˈpæk/', '/ˈpɛk/'),
  ('æ_e', '/æ/ – /e/', 'vowel', 'bland', 'blend', '/ˈblænd/', '/ˈblɛnd/'),
  ('æ_e', '/æ/ – /e/', 'vowel', 'batter', 'better', '/ˈbætər/', '/ˈbɛtər/'),
  ('æ_e', '/æ/ – /e/', 'vowel', 'latter', 'letter', '/ˈlætər/', '/ˈlɛtər/'),
  ('æ_e', '/æ/ – /e/', 'vowel', 'cattle', 'kettle', '/ˈkætəl/', '/ˈkɛtəl/'),
  ('æ_e', '/æ/ – /e/', 'vowel', 'vat', 'vet', '/ˈvæt/', '/ˈvɛt/'),
  ('æ_e', '/æ/ – /e/', 'vowel', 'than', 'then', '/ˈðæn/', '/ˈðɛn/'),
  ('æ_e', '/æ/ – /e/', 'vowel', 'sax', 'sex', '/ˈsæks/', '/ˈsɛks/'),
  ('æ_e', '/æ/ – /e/', 'vowel', 'shall', 'shell', '/ˈʃæl/', '/ˈʃɛl/'),
  ('æ_e', '/æ/ – /e/', 'vowel', 'paddle', 'peddle', '/ˈpædəl/', '/ˈpɛdəl/'),
  ('æ_e', '/æ/ – /e/', 'vowel', 'salary', 'celery', '/ˈsæləriː/', '/ˈsɛləriː/'),
  ('æ_e', '/æ/ – /e/', 'vowel', 'ham', 'hem', '/ˈhæm/', '/ˈhɛm/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'cat', 'cut', '/ˈkæt/', '/ˈkʌt/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'bat', 'but', '/ˈbæt/', '/ˈbʌt/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'hat', 'hut', '/ˈhæt/', '/ˈhʌt/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'cap', 'cup', '/ˈkæp/', '/ˈkʌp/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'bag', 'bug', '/ˈbæɡ/', '/ˈbʌɡ/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'ran', 'run', '/ˈræn/', '/ˈrʌn/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'ankle', 'uncle', '/ˈæŋkəl/', '/ˈʌŋkəl/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'match', 'much', '/ˈmætʃ/', '/ˈmʌtʃ/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'mad', 'mud', '/ˈmæd/', '/ˈmʌd/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'bad', 'bud', '/ˈbæd/', '/ˈbʌd/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'ban', 'bun', '/ˈbæn/', '/ˈbʌn/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'fan', 'fun', '/ˈfæn/', '/ˈfʌn/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'sank', 'sunk', '/ˈsæŋk/', '/ˈsʌŋk/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'rang', 'rung', '/ˈræŋ/', '/ˈrʌŋ/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'sang', 'sung', '/ˈsæŋ/', '/ˈsʌŋ/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'drank', 'drunk', '/ˈdræŋk/', '/ˈdrʌŋk/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'stack', 'stuck', '/ˈstæk/', '/ˈstʌk/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'track', 'truck', '/ˈtræk/', '/ˈtrʌk/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'lack', 'luck', '/ˈlæk/', '/ˈlʌk/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'back', 'buck', '/ˈbæk/', '/ˈbʌk/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'hang', 'hung', '/ˈhæŋ/', '/ˈhʌŋ/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'ham', 'hum', '/ˈhæm/', '/ˈhʌm/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'pat', 'putt', '/ˈpæt/', '/ˈpʌt/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'rat', 'rut', '/ˈræt/', '/ˈrʌt/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'cab', 'cub', '/ˈkæb/', '/ˈkʌb/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'crash', 'crush', '/ˈkræʃ/', '/ˈkrʌʃ/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'brash', 'brush', '/ˈbræʃ/', '/ˈbrʌʃ/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'flash', 'flush', '/ˈflæʃ/', '/ˈflʌʃ/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'slash', 'slush', '/ˈslæʃ/', '/ˈslʌʃ/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'pan', 'pun', '/ˈpæn/', '/ˈpʌn/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'lamp', 'lump', '/ˈlæmp/', '/ˈlʌmp/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'damp', 'dump', '/ˈdæmp/', '/ˈdʌmp/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'stamp', 'stump', '/ˈstæmp/', '/ˈstʌmp/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'tan', 'ton', '/ˈtæn/', '/ˈtʌn/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'swam', 'swum', '/ˈswæm/', '/ˈswʌm/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'sack', 'suck', '/ˈsæk/', '/ˈsʌk/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'dabble', 'double', '/ˈdæbəl/', '/ˈdʌbəl/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'badge', 'budge', '/ˈbædʒ/', '/ˈbʌdʒ/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'batter', 'butter', '/ˈbætər/', '/ˈbʌtər/'),
  ('æ_ʌ', '/æ/ – /ʌ/', 'vowel', 'mash', 'mush', '/ˈmæʃ/', '/ˈmʌʃ/'),
  ('e_ʌ', '/e/ – /ʌ/', 'vowel', 'bed', 'bud', '/ˈbɛd/', '/ˈbʌd/'),
  ('e_ʌ', '/e/ – /ʌ/', 'vowel', 'beg', 'bug', '/ˈbɛɡ/', '/ˈbʌɡ/'),
  ('e_ʌ', '/e/ – /ʌ/', 'vowel', 'ten', 'ton', '/ˈtɛn/', '/ˈtʌn/'),
  ('e_ʌ', '/e/ – /ʌ/', 'vowel', 'net', 'nut', '/ˈnɛt/', '/ˈnʌt/'),
  ('e_ʌ', '/e/ – /ʌ/', 'vowel', 'bet', 'but', '/ˈbɛt/', '/ˈbʌt/'),
  ('e_ʌ', '/e/ – /ʌ/', 'vowel', 'get', 'gut', '/ˈɡɛt/', '/ˈɡʌt/'),
  ('e_ʌ', '/e/ – /ʌ/', 'vowel', 'met', 'mutt', '/ˈmɛt/', '/ˈmʌt/'),
  ('e_ʌ', '/e/ – /ʌ/', 'vowel', 'pet', 'putt', '/ˈpɛt/', '/ˈpʌt/'),
  ('e_ʌ', '/e/ – /ʌ/', 'vowel', 'hem', 'hum', '/ˈhɛm/', '/ˈhʌm/'),
  ('e_ʌ', '/e/ – /ʌ/', 'vowel', 'best', 'bust', '/ˈbɛst/', '/ˈbʌst/'),
  ('e_ʌ', '/e/ – /ʌ/', 'vowel', 'rest', 'rust', '/ˈrɛst/', '/ˈrʌst/'),
  ('e_ʌ', '/e/ – /ʌ/', 'vowel', 'dead', 'dud', '/ˈdɛd/', '/ˈdʌd/'),
  ('e_ʌ', '/e/ – /ʌ/', 'vowel', 'check', 'chuck', '/ˈtʃɛk/', '/ˈtʃʌk/'),
  ('e_ʌ', '/e/ – /ʌ/', 'vowel', 'deck', 'duck', '/ˈdɛk/', '/ˈdʌk/'),
  ('e_ʌ', '/e/ – /ʌ/', 'vowel', 'peck', 'puck', '/ˈpɛk/', '/ˈpʌk/'),
  ('e_ʌ', '/e/ – /ʌ/', 'vowel', 'trek', 'truck', '/ˈtrɛk/', '/ˈtrʌk/'),
  ('e_ʌ', '/e/ – /ʌ/', 'vowel', 'hell', 'hull', '/ˈhɛl/', '/ˈhʌl/'),
  ('e_ʌ', '/e/ – /ʌ/', 'vowel', 'bench', 'bunch', '/ˈbɛntʃ/', '/ˈbʌntʃ/'),
  ('e_ʌ', '/e/ – /ʌ/', 'vowel', 'fend', 'fund', '/ˈfɛnd/', '/ˈfʌnd/'),
  ('e_ʌ', '/e/ – /ʌ/', 'vowel', 'den', 'done', '/ˈdɛn/', '/ˈdʌn/'),
  ('e_ʌ', '/e/ – /ʌ/', 'vowel', 'pen', 'pun', '/ˈpɛn/', '/ˈpʌn/'),
  ('e_ʌ', '/e/ – /ʌ/', 'vowel', 'wren', 'run', '/ˈrɛn/', '/ˈrʌn/'),
  ('e_ʌ', '/e/ – /ʌ/', 'vowel', 'jet', 'jut', '/ˈdʒɛt/', '/ˈdʒʌt/'),
  ('e_ʌ', '/e/ – /ʌ/', 'vowel', 'bled', 'blood', '/ˈblɛd/', '/ˈblʌd/'),
  ('e_ʌ', '/e/ – /ʌ/', 'vowel', 'fled', 'flood', '/ˈflɛd/', '/ˈflʌd/'),
  ('e_ʌ', '/e/ – /ʌ/', 'vowel', 'sped', 'spud', '/ˈspɛd/', '/ˈspʌd/'),
  ('ɒ_ɔː', '/ɒ/ – /ɔː/', 'vowel', 'don', 'dawn', '/ˈdɑn/', '/ˈdɔn/'),
  ('ɒ_ɔː', '/ɒ/ – /ɔː/', 'vowel', 'hock', 'hawk', '/ˈhɑk/', '/ˈhɔk/'),
  ('ɒ_ɔː', '/ɒ/ – /ɔː/', 'vowel', 'stock', 'stalk', '/ˈstɑk/', '/ˈstɔk/'),
  ('ɒ_ɔː', '/ɒ/ – /ɔː/', 'vowel', 'tot', 'taught', '/ˈtɑt/', '/ˈtɔt/'),
  ('ɒ_ɔː', '/ɒ/ – /ɔː/', 'vowel', 'not', 'naught', '/ˈnɑt/', '/ˈnɔt/'),
  ('ɒ_ɔː', '/ɒ/ – /ɔː/', 'vowel', 'knotty', 'naughty', '/ˈnɑtiː/', '/ˈnɔtiː/'),
  ('ɒ_ɔː', '/ɒ/ – /ɔː/', 'vowel', 'odd', 'awed', '/ˈɑd/', '/ˈɔd/'),
  ('ɒ_ɔː', '/ɒ/ – /ɔː/', 'vowel', 'nod', 'gnawed', '/ˈnɑd/', '/ˈnɔd/'),
  ('ɒ_ɔː', '/ɒ/ – /ɔː/', 'vowel', 'pod', 'pawed', '/ˈpɑd/', '/ˈpɔd/'),
  ('ɒ_ɔː', '/ɒ/ – /ɔː/', 'vowel', 'collar', 'caller', '/ˈkɑlər/', '/ˈkɔlər/'),
  ('ɒ_ɔː', '/ɒ/ – /ɔː/', 'vowel', 'wok', 'walk', '/ˈwɑk/', '/ˈwɔk/'),
  ('ɒ_ɔː', '/ɒ/ – /ɔː/', 'vowel', 'pond', 'pawned', '/ˈpɑnd/', '/ˈpɔnd/'),
  ('ʊ_uː', '/ʊ/ – /uː/', 'vowel', 'full', 'fool', '/ˈfʊl/', '/ˈfuːl/'),
  ('ʊ_uː', '/ʊ/ – /uː/', 'vowel', 'pull', 'pool', '/ˈpʊl/', '/ˈpuːl/'),
  ('ʊ_uː', '/ʊ/ – /uː/', 'vowel', 'look', 'luke', '/ˈlʊk/', '/ˈluːk/'),
  ('ʊ_uː', '/ʊ/ – /uː/', 'vowel', 'cook', 'kook', '/ˈkʊk/', '/ˈkuːk/'),
  ('ʊ_uː', '/ʊ/ – /uː/', 'vowel', 'nook', 'nuke', '/ˈnʊk/', '/ˈnuːk/'),
  ('ʊ_uː', '/ʊ/ – /uː/', 'vowel', 'could', 'cooed', '/ˈkʊd/', '/ˈkuːd/'),
  ('ʊ_uː', '/ʊ/ – /uː/', 'vowel', 'would', 'wooed', '/ˈwʊd/', '/ˈwuːd/'),
  ('ʊ_uː', '/ʊ/ – /uː/', 'vowel', 'should', 'shooed', '/ˈʃʊd/', '/ˈʃuːd/'),
  ('ʊ_uː', '/ʊ/ – /uː/', 'vowel', 'stood', 'stewed', '/ˈstʊd/', '/ˈstuːd/'),
  ('ʊ_uː', '/ʊ/ – /uː/', 'vowel', 'hood', 'who''d', '/ˈhʊd/', '/ˈhuːd/'),
  ('ʊ_uː', '/ʊ/ – /uː/', 'vowel', 'soot', 'suit', '/ˈsʊt/', '/ˈsuːt/'),
  ('ʊ_uː', '/ʊ/ – /uː/', 'vowel', 'wood', 'wooed', '/ˈwʊd/', '/ˈwuːd/'),
  ('ʊ_uː', '/ʊ/ – /uː/', 'vowel', 'pulling', 'pooling', '/ˈpʊlɪŋ/', '/ˈpuːlɪŋ/'),
  ('θ_s', '/θ/ – /s/', 'consonant', 'think', 'sink', '/ˈθɪŋk/', '/ˈsɪŋk/'),
  ('θ_s', '/θ/ – /s/', 'consonant', 'thick', 'sick', '/ˈθɪk/', '/ˈsɪk/'),
  ('θ_s', '/θ/ – /s/', 'consonant', 'thin', 'sin', '/ˈθɪn/', '/ˈsɪn/'),
  ('θ_s', '/θ/ – /s/', 'consonant', 'thing', 'sing', '/ˈθɪŋ/', '/ˈsɪŋ/'),
  ('θ_s', '/θ/ – /s/', 'consonant', 'thumb', 'sum', '/ˈθʌm/', '/ˈsʌm/'),
  ('θ_s', '/θ/ – /s/', 'consonant', 'theme', 'seem', '/ˈθiːm/', '/ˈsiːm/'),
  ('θ_s', '/θ/ – /s/', 'consonant', 'thought', 'sought', '/ˈθɔt/', '/ˈsɔt/'),
  ('θ_s', '/θ/ – /s/', 'consonant', 'path', 'pass', '/ˈpæθ/', '/ˈpæs/'),
  ('θ_s', '/θ/ – /s/', 'consonant', 'bath', 'bass', '/ˈbæθ/', '/ˈbæs/'),
  ('θ_s', '/θ/ – /s/', 'consonant', 'math', 'mass', '/ˈmæθ/', '/ˈmæs/'),
  ('θ_s', '/θ/ – /s/', 'consonant', 'mouth', 'mouse', '/ˈmaʊθ/', '/ˈmaʊs/'),
  ('θ_s', '/θ/ – /s/', 'consonant', 'tenth', 'tense', '/ˈtɛnθ/', '/ˈtɛns/'),
  ('θ_s', '/θ/ – /s/', 'consonant', 'worth', 'worse', '/ˈwɜrθ/', '/ˈwɜrs/'),
  ('θ_s', '/θ/ – /s/', 'consonant', 'faith', 'face', '/ˈfeɪθ/', '/ˈfeɪs/'),
  ('θ_s', '/θ/ – /s/', 'consonant', 'truth', 'truce', '/ˈtruːθ/', '/ˈtruːs/'),
  ('θ_s', '/θ/ – /s/', 'consonant', 'myth', 'miss', '/ˈmɪθ/', '/ˈmɪs/'),
  ('θ_s', '/θ/ – /s/', 'consonant', 'moth', 'moss', '/ˈmɔθ/', '/ˈmɔs/'),
  ('θ_s', '/θ/ – /s/', 'consonant', 'fourth', 'force', '/ˈfɔrθ/', '/ˈfɔrs/'),
  ('θ_s', '/θ/ – /s/', 'consonant', 'youth', 'use', '/ˈjuːθ/', '/ˈjuːs/'),
  ('θ_s', '/θ/ – /s/', 'consonant', 'growth', 'gross', '/ˈɡroʊθ/', '/ˈɡroʊs/'),
  ('θ_s', '/θ/ – /s/', 'consonant', 'thank', 'sank', '/ˈθæŋk/', '/ˈsæŋk/'),
  ('θ_s', '/θ/ – /s/', 'consonant', 'thigh', 'sigh', '/ˈθaɪ/', '/ˈsaɪ/'),
  ('θ_s', '/θ/ – /s/', 'consonant', 'thaw', 'saw', '/ˈθɔ/', '/ˈsɔ/'),
  ('θ_s', '/θ/ – /s/', 'consonant', 'thong', 'song', '/ˈθɔŋ/', '/ˈsɔŋ/'),
  ('θ_s', '/θ/ – /s/', 'consonant', 'thinking', 'sinking', '/ˈθɪŋkɪŋ/', '/ˈsɪŋkɪŋ/'),
  ('θ_s', '/θ/ – /s/', 'consonant', 'thumbs', 'sums', '/ˈθʌmz/', '/ˈsʌmz/'),
  ('θ_s', '/θ/ – /s/', 'consonant', 'thinks', 'sinks', '/ˈθɪŋks/', '/ˈsɪŋks/'),
  ('ð_d', '/ð/ – /d/', 'consonant', 'they', 'day', '/ˈðeɪ/', '/ˈdeɪ/'),
  ('ð_d', '/ð/ – /d/', 'consonant', 'then', 'den', '/ˈðɛn/', '/ˈdɛn/'),
  ('ð_d', '/ð/ – /d/', 'consonant', 'there', 'dare', '/ˈðɛr/', '/ˈdɛr/'),
  ('ð_d', '/ð/ – /d/', 'consonant', 'those', 'doze', '/ˈðoʊz/', '/ˈdoʊz/'),
  ('ð_d', '/ð/ – /d/', 'consonant', 'though', 'dough', '/ˈðoʊ/', '/ˈdoʊ/'),
  ('ð_d', '/ð/ – /d/', 'consonant', 'thy', 'die', '/ˈðaɪ/', '/ˈdaɪ/'),
  ('ð_d', '/ð/ – /d/', 'consonant', 'breathe', 'breed', '/ˈbriːð/', '/ˈbriːd/'),
  ('ð_d', '/ð/ – /d/', 'consonant', 'bathe', 'bade', '/ˈbeɪð/', '/ˈbeɪd/'),
  ('ð_d', '/ð/ – /d/', 'consonant', 'lather', 'ladder', '/ˈlæðər/', '/ˈlædər/'),
  ('ð_d', '/ð/ – /d/', 'consonant', 'father', 'fodder', '/ˈfɑðər/', '/ˈfɑdər/'),
  ('ð_d', '/ð/ – /d/', 'consonant', 'loathe', 'load', '/ˈloʊð/', '/ˈloʊd/'),
  ('ð_d', '/ð/ – /d/', 'consonant', 'lathe', 'laid', '/ˈleɪð/', '/ˈleɪd/'),
  ('ð_d', '/ð/ – /d/', 'consonant', 'seethe', 'seed', '/ˈsiːð/', '/ˈsiːd/'),
  ('ð_d', '/ð/ – /d/', 'consonant', 'soothe', 'sued', '/ˈsuːð/', '/ˈsuːd/'),
  ('ð_d', '/ð/ – /d/', 'consonant', 'worthy', 'wordy', '/ˈwɜrðiː/', '/ˈwɜrdiː/'),
  ('ð_d', '/ð/ – /d/', 'consonant', 'tithe', 'tide', '/ˈtaɪð/', '/ˈtaɪd/'),
  ('ð_d', '/ð/ – /d/', 'consonant', 'heather', 'header', '/ˈhɛðər/', '/ˈhɛdər/'),
  ('v_w', '/v/ – /w/', 'consonant', 'vest', 'west', '/ˈvɛst/', '/ˈwɛst/'),
  ('v_w', '/v/ – /w/', 'consonant', 'vet', 'wet', '/ˈvɛt/', '/ˈwɛt/'),
  ('v_w', '/v/ – /w/', 'consonant', 'vine', 'wine', '/ˈvaɪn/', '/ˈwaɪn/'),
  ('v_w', '/v/ – /w/', 'consonant', 'vine', 'whine', '/ˈvaɪn/', '/ˈwaɪn/'),
  ('v_w', '/v/ – /w/', 'consonant', 'veil', 'whale', '/ˈveɪl/', '/ˈweɪl/'),
  ('v_w', '/v/ – /w/', 'consonant', 'vary', 'wary', '/ˈvɛriː/', '/ˈwɛriː/'),
  ('v_w', '/v/ – /w/', 'consonant', 'verse', 'worse', '/ˈvɜrs/', '/ˈwɜrs/'),
  ('v_w', '/v/ – /w/', 'consonant', 'vow', 'wow', '/ˈvaʊ/', '/ˈwaʊ/'),
  ('v_w', '/v/ – /w/', 'consonant', 'veal', 'wheel', '/ˈviːl/', '/ˈwiːl/'),
  ('v_w', '/v/ – /w/', 'consonant', 'vent', 'went', '/ˈvɛnt/', '/ˈwɛnt/'),
  ('v_w', '/v/ – /w/', 'consonant', 'viper', 'wiper', '/ˈvaɪpər/', '/ˈwaɪpər/'),
  ('v_w', '/v/ – /w/', 'consonant', 'vile', 'while', '/ˈvaɪl/', '/ˈwaɪl/'),
  ('v_w', '/v/ – /w/', 'consonant', 'vain', 'wane', '/ˈveɪn/', '/ˈweɪn/'),
  ('v_w', '/v/ – /w/', 'consonant', 'very', 'wary', '/ˈvɛriː/', '/ˈwɛriː/'),
  ('v_w', '/v/ – /w/', 'consonant', 'visor', 'wiser', '/ˈvaɪzər/', '/ˈwaɪzər/'),
  ('v_w', '/v/ – /w/', 'consonant', 'vowed', 'wowed', '/ˈvaʊd/', '/ˈwaʊd/'),
  ('v_w', '/v/ – /w/', 'consonant', 'vicar', 'wicker', '/ˈvɪkər/', '/ˈwɪkər/'),
  ('ʃ_s', '/ʃ/ – /s/', 'consonant', 'she', 'see', '/ˈʃiː/', '/ˈsiː/'),
  ('ʃ_s', '/ʃ/ – /s/', 'consonant', 'ship', 'sip', '/ˈʃɪp/', '/ˈsɪp/'),
  ('ʃ_s', '/ʃ/ – /s/', 'consonant', 'shy', 'sigh', '/ˈʃaɪ/', '/ˈsaɪ/'),
  ('ʃ_s', '/ʃ/ – /s/', 'consonant', 'sheet', 'seat', '/ˈʃiːt/', '/ˈsiːt/'),
  ('ʃ_s', '/ʃ/ – /s/', 'consonant', 'sheep', 'seep', '/ˈʃiːp/', '/ˈsiːp/'),
  ('ʃ_s', '/ʃ/ – /s/', 'consonant', 'shell', 'sell', '/ˈʃɛl/', '/ˈsɛl/'),
  ('ʃ_s', '/ʃ/ – /s/', 'consonant', 'shore', 'sore', '/ˈʃɔr/', '/ˈsɔr/'),
  ('ʃ_s', '/ʃ/ – /s/', 'consonant', 'shine', 'sign', '/ˈʃaɪn/', '/ˈsaɪn/'),
  ('ʃ_s', '/ʃ/ – /s/', 'consonant', 'shoe', 'sue', '/ˈʃuː/', '/ˈsuː/'),
  ('ʃ_s', '/ʃ/ – /s/', 'consonant', 'show', 'sew', '/ˈʃoʊ/', '/ˈsoʊ/'),
  ('ʃ_s', '/ʃ/ – /s/', 'consonant', 'shock', 'sock', '/ˈʃɑk/', '/ˈsɑk/'),
  ('ʃ_s', '/ʃ/ – /s/', 'consonant', 'shave', 'save', '/ˈʃeɪv/', '/ˈseɪv/'),
  ('ʃ_s', '/ʃ/ – /s/', 'consonant', 'shame', 'same', '/ˈʃeɪm/', '/ˈseɪm/'),
  ('ʃ_s', '/ʃ/ – /s/', 'consonant', 'shed', 'said', '/ˈʃɛd/', '/ˈsɛd/'),
  ('ʃ_s', '/ʃ/ – /s/', 'consonant', 'shack', 'sack', '/ˈʃæk/', '/ˈsæk/'),
  ('ʃ_s', '/ʃ/ – /s/', 'consonant', 'shift', 'sift', '/ˈʃɪft/', '/ˈsɪft/'),
  ('ʃ_s', '/ʃ/ – /s/', 'consonant', 'shun', 'sun', '/ˈʃʌn/', '/ˈsʌn/'),
  ('ʃ_s', '/ʃ/ – /s/', 'consonant', 'mesh', 'mess', '/ˈmɛʃ/', '/ˈmɛs/'),
  ('ʃ_s', '/ʃ/ – /s/', 'consonant', 'lash', 'lass', '/ˈlæʃ/', '/ˈlæs/'),
  ('ʃ_s', '/ʃ/ – /s/', 'consonant', 'gash', 'gas', '/ˈɡæʃ/', '/ˈɡæs/'),
  ('ʃ_s', '/ʃ/ – /s/', 'consonant', 'mash', 'mass', '/ˈmæʃ/', '/ˈmæs/'),
  ('ʃ_s', '/ʃ/ – /s/', 'consonant', 'bash', 'bass', '/ˈbæʃ/', '/ˈbæs/'),
  ('ʃ_s', '/ʃ/ – /s/', 'consonant', 'leash', 'lease', '/ˈliːʃ/', '/ˈliːs/'),
  ('ʃ_s', '/ʃ/ – /s/', 'consonant', 'plush', 'plus', '/ˈplʌʃ/', '/ˈplʌs/'),
  ('ʃ_s', '/ʃ/ – /s/', 'consonant', 'shoot', 'suit', '/ˈʃuːt/', '/ˈsuːt/'),
  ('ʃ_s', '/ʃ/ – /s/', 'consonant', 'short', 'sort', '/ˈʃɔrt/', '/ˈsɔrt/'),
  ('ʃ_s', '/ʃ/ – /s/', 'consonant', 'shin', 'sin', '/ˈʃɪn/', '/ˈsɪn/'),
  ('ʃ_s', '/ʃ/ – /s/', 'consonant', 'shingle', 'single', '/ˈʃɪŋɡəl/', '/ˈsɪŋɡəl/'),
  ('ʃ_s', '/ʃ/ – /s/', 'consonant', 'shake', 'sake', '/ˈʃeɪk/', '/ˈseɪk/'),
  ('ʃ_s', '/ʃ/ – /s/', 'consonant', 'shale', 'sale', '/ˈʃeɪl/', '/ˈseɪl/'),
  ('ʃ_s', '/ʃ/ – /s/', 'consonant', 'shorts', 'sorts', '/ˈʃɔrts/', '/ˈsɔrts/'),
  ('tʃ_dʒ', '/tʃ/ – /dʒ/', 'consonant', 'chin', 'gin', '/ˈtʃɪn/', '/ˈdʒɪn/'),
  ('tʃ_dʒ', '/tʃ/ – /dʒ/', 'consonant', 'cheap', 'jeep', '/ˈtʃiːp/', '/ˈdʒiːp/'),
  ('tʃ_dʒ', '/tʃ/ – /dʒ/', 'consonant', 'choke', 'joke', '/ˈtʃoʊk/', '/ˈdʒoʊk/'),
  ('tʃ_dʒ', '/tʃ/ – /dʒ/', 'consonant', 'chest', 'jest', '/ˈtʃɛst/', '/ˈdʒɛst/'),
  ('tʃ_dʒ', '/tʃ/ – /dʒ/', 'consonant', 'chunk', 'junk', '/ˈtʃʌŋk/', '/ˈdʒʌŋk/'),
  ('tʃ_dʒ', '/tʃ/ – /dʒ/', 'consonant', 'cheer', 'jeer', '/ˈtʃɪr/', '/ˈdʒɪr/'),
  ('tʃ_dʒ', '/tʃ/ – /dʒ/', 'consonant', 'char', 'jar', '/ˈtʃɑr/', '/ˈdʒɑr/'),
  ('tʃ_dʒ', '/tʃ/ – /dʒ/', 'consonant', 'chug', 'jug', '/ˈtʃʌɡ/', '/ˈdʒʌɡ/'),
  ('tʃ_dʒ', '/tʃ/ – /dʒ/', 'consonant', 'batch', 'badge', '/ˈbætʃ/', '/ˈbædʒ/'),
  ('tʃ_dʒ', '/tʃ/ – /dʒ/', 'consonant', 'rich', 'ridge', '/ˈrɪtʃ/', '/ˈrɪdʒ/'),
  ('tʃ_dʒ', '/tʃ/ – /dʒ/', 'consonant', 'lunch', 'lunge', '/ˈlʌntʃ/', '/ˈlʌndʒ/'),
  ('tʃ_dʒ', '/tʃ/ – /dʒ/', 'consonant', 'search', 'surge', '/ˈsɜrtʃ/', '/ˈsɜrdʒ/'),
  ('tʃ_dʒ', '/tʃ/ – /dʒ/', 'consonant', 'perch', 'purge', '/ˈpɜrtʃ/', '/ˈpɜrdʒ/'),
  ('tʃ_dʒ', '/tʃ/ – /dʒ/', 'consonant', 'larch', 'large', '/ˈlɑrtʃ/', '/ˈlɑrdʒ/'),
  ('tʃ_dʒ', '/tʃ/ – /dʒ/', 'consonant', 'etch', 'edge', '/ˈɛtʃ/', '/ˈɛdʒ/'),
  ('tʃ_dʒ', '/tʃ/ – /dʒ/', 'consonant', 'riches', 'ridges', '/ˈrɪtʃəz/', '/ˈrɪdʒəz/'),
  ('tʃ_dʒ', '/tʃ/ – /dʒ/', 'consonant', 'cinch', 'singe', '/ˈsɪntʃ/', '/ˈsɪndʒ/'),
  ('tʃ_dʒ', '/tʃ/ – /dʒ/', 'consonant', 'chump', 'jump', '/ˈtʃʌmp/', '/ˈdʒʌmp/'),
  ('tʃ_dʒ', '/tʃ/ – /dʒ/', 'consonant', 'chock', 'jock', '/ˈtʃɑk/', '/ˈdʒɑk/'),
  ('r_l', '/r/ – /l/', 'consonant', 'right', 'light', '/ˈraɪt/', '/ˈlaɪt/'),
  ('r_l', '/r/ – /l/', 'consonant', 'road', 'load', '/ˈroʊd/', '/ˈloʊd/'),
  ('r_l', '/r/ – /l/', 'consonant', 'rock', 'lock', '/ˈrɑk/', '/ˈlɑk/'),
  ('r_l', '/r/ – /l/', 'consonant', 'red', 'led', '/ˈrɛd/', '/ˈlɛd/'),
  ('r_l', '/r/ – /l/', 'consonant', 'rice', 'lice', '/ˈraɪs/', '/ˈlaɪs/'),
  ('r_l', '/r/ – /l/', 'consonant', 'rip', 'lip', '/ˈrɪp/', '/ˈlɪp/'),
  ('r_l', '/r/ – /l/', 'consonant', 'race', 'lace', '/ˈreɪs/', '/ˈleɪs/'),
  ('r_l', '/r/ – /l/', 'consonant', 'rate', 'late', '/ˈreɪt/', '/ˈleɪt/'),
  ('r_l', '/r/ – /l/', 'consonant', 'rain', 'lane', '/ˈreɪn/', '/ˈleɪn/'),
  ('r_l', '/r/ – /l/', 'consonant', 'row', 'low', '/ˈroʊ/', '/ˈloʊ/'),
  ('r_l', '/r/ – /l/', 'consonant', 'rush', 'lush', '/ˈrʌʃ/', '/ˈlʌʃ/'),
  ('r_l', '/r/ – /l/', 'consonant', 'ram', 'lamb', '/ˈræm/', '/ˈlæm/'),
  ('r_l', '/r/ – /l/', 'consonant', 'rack', 'lack', '/ˈræk/', '/ˈlæk/'),
  ('r_l', '/r/ – /l/', 'consonant', 'rap', 'lap', '/ˈræp/', '/ˈlæp/'),
  ('r_l', '/r/ – /l/', 'consonant', 'rag', 'lag', '/ˈræɡ/', '/ˈlæɡ/'),
  ('r_l', '/r/ – /l/', 'consonant', 'rid', 'lid', '/ˈrɪd/', '/ˈlɪd/'),
  ('r_l', '/r/ – /l/', 'consonant', 'rift', 'lift', '/ˈrɪft/', '/ˈlɪft/'),
  ('r_l', '/r/ – /l/', 'consonant', 'room', 'loom', '/ˈruːm/', '/ˈluːm/'),
  ('r_l', '/r/ – /l/', 'consonant', 'root', 'loot', '/ˈruːt/', '/ˈluːt/'),
  ('r_l', '/r/ – /l/', 'consonant', 'rust', 'lust', '/ˈrʌst/', '/ˈlʌst/'),
  ('r_l', '/r/ – /l/', 'consonant', 'wrong', 'long', '/ˈrɔŋ/', '/ˈlɔŋ/'),
  ('r_l', '/r/ – /l/', 'consonant', 'reef', 'leaf', '/ˈriːf/', '/ˈliːf/'),
  ('r_l', '/r/ – /l/', 'consonant', 'reap', 'leap', '/ˈriːp/', '/ˈliːp/'),
  ('r_l', '/r/ – /l/', 'consonant', 'ride', 'lied', '/ˈraɪd/', '/ˈlaɪd/'),
  ('r_l', '/r/ – /l/', 'consonant', 'rye', 'lie', '/ˈraɪ/', '/ˈlaɪ/'),
  ('r_l', '/r/ – /l/', 'consonant', 'rest', 'lest', '/ˈrɛst/', '/ˈlɛst/'),
  ('r_l', '/r/ – /l/', 'consonant', 'rung', 'lung', '/ˈrʌŋ/', '/ˈlʌŋ/'),
  ('r_l', '/r/ – /l/', 'consonant', 'rob', 'lob', '/ˈrɑb/', '/ˈlɑb/'),
  ('r_l', '/r/ – /l/', 'consonant', 'rot', 'lot', '/ˈrɑt/', '/ˈlɑt/'),
  ('r_l', '/r/ – /l/', 'consonant', 'raid', 'laid', '/ˈreɪd/', '/ˈleɪd/'),
  ('r_l', '/r/ – /l/', 'consonant', 'rake', 'lake', '/ˈreɪk/', '/ˈleɪk/'),
  ('r_l', '/r/ – /l/', 'consonant', 'ramp', 'lamp', '/ˈræmp/', '/ˈlæmp/'),
  ('r_l', '/r/ – /l/', 'consonant', 'rash', 'lash', '/ˈræʃ/', '/ˈlæʃ/'),
  ('r_l', '/r/ – /l/', 'consonant', 'pray', 'play', '/ˈpreɪ/', '/ˈpleɪ/'),
  ('r_l', '/r/ – /l/', 'consonant', 'crowd', 'cloud', '/ˈkraʊd/', '/ˈklaʊd/'),
  ('r_l', '/r/ – /l/', 'consonant', 'crash', 'clash', '/ˈkræʃ/', '/ˈklæʃ/'),
  ('r_l', '/r/ – /l/', 'consonant', 'grass', 'glass', '/ˈɡræs/', '/ˈɡlæs/'),
  ('r_l', '/r/ – /l/', 'consonant', 'brush', 'blush', '/ˈbrʌʃ/', '/ˈblʌʃ/'),
  ('r_l', '/r/ – /l/', 'consonant', 'crown', 'clown', '/ˈkraʊn/', '/ˈklaʊn/'),
  ('r_l', '/r/ – /l/', 'consonant', 'fry', 'fly', '/ˈfraɪ/', '/ˈflaɪ/'),
  ('r_l', '/r/ – /l/', 'consonant', 'free', 'flee', '/ˈfriː/', '/ˈfliː/'),
  ('r_l', '/r/ – /l/', 'consonant', 'frame', 'flame', '/ˈfreɪm/', '/ˈfleɪm/'),
  ('r_l', '/r/ – /l/', 'consonant', 'grow', 'glow', '/ˈɡroʊ/', '/ˈɡloʊ/'),
  ('r_l', '/r/ – /l/', 'consonant', 'bread', 'bled', '/ˈbrɛd/', '/ˈblɛd/'),
  ('r_l', '/r/ – /l/', 'consonant', 'crime', 'climb', '/ˈkraɪm/', '/ˈklaɪm/'),
  ('r_l', '/r/ – /l/', 'consonant', 'fresh', 'flesh', '/ˈfrɛʃ/', '/ˈflɛʃ/'),
  ('r_l', '/r/ – /l/', 'consonant', 'fright', 'flight', '/ˈfraɪt/', '/ˈflaɪt/'),
  ('r_l', '/r/ – /l/', 'consonant', 'broom', 'bloom', '/ˈbruːm/', '/ˈbluːm/'),
  ('r_l', '/r/ – /l/', 'consonant', 'brand', 'bland', '/ˈbrænd/', '/ˈblænd/'),
  ('r_l', '/r/ – /l/', 'consonant', 'brew', 'blue', '/ˈbruː/', '/ˈbluː/'),
  ('r_l', '/r/ – /l/', 'consonant', 'cram', 'clam', '/ˈkræm/', '/ˈklæm/'),
  ('r_l', '/r/ – /l/', 'consonant', 'berry', 'belly', '/ˈbɛriː/', '/ˈbɛliː/'),
  ('r_l', '/r/ – /l/', 'consonant', 'grammar', 'glamour', '/ˈɡræmər/', '/ˈɡlæmər/'),
  ('r_l', '/r/ – /l/', 'consonant', 'pirate', 'pilot', '/ˈpaɪrət/', '/ˈpaɪlət/'),
  ('final_s_z', '/s/ – /z/ (cuối từ)', 'final', 'bus', 'buzz', '/ˈbʌs/', '/ˈbʌz/'),
  ('final_s_z', '/s/ – /z/ (cuối từ)', 'final', 'place', 'plays', '/ˈpleɪs/', '/ˈpleɪz/'),
  ('final_s_z', '/s/ – /z/ (cuối từ)', 'final', 'rice', 'rise', '/ˈraɪs/', '/ˈraɪz/'),
  ('final_s_z', '/s/ – /z/ (cuối từ)', 'final', 'peace', 'peas', '/ˈpiːs/', '/ˈpiːz/'),
  ('final_s_z', '/s/ – /z/ (cuối từ)', 'final', 'price', 'prize', '/ˈpraɪs/', '/ˈpraɪz/'),
  ('final_s_z', '/s/ – /z/ (cuối từ)', 'final', 'race', 'raise', '/ˈreɪs/', '/ˈreɪz/'),
  ('final_s_z', '/s/ – /z/ (cuối từ)', 'final', 'loose', 'lose', '/ˈluːs/', '/ˈluːz/'),
  ('final_s_z', '/s/ – /z/ (cuối từ)', 'final', 'ice', 'eyes', '/ˈaɪs/', '/ˈaɪz/'),
  ('final_s_z', '/s/ – /z/ (cuối từ)', 'final', 'face', 'phase', '/ˈfeɪs/', '/ˈfeɪz/'),
  ('final_s_z', '/s/ – /z/ (cuối từ)', 'final', 'false', 'falls', '/ˈfɔls/', '/ˈfɔlz/'),
  ('final_s_z', '/s/ – /z/ (cuối từ)', 'final', 'niece', 'knees', '/ˈniːs/', '/ˈniːz/'),
  ('final_s_z', '/s/ – /z/ (cuối từ)', 'final', 'once', 'ones', '/ˈwʌns/', '/ˈwʌnz/'),
  ('final_s_z', '/s/ – /z/ (cuối từ)', 'final', 'advice', 'advise', '/æˈdvaɪs/', '/æˈdvaɪz/'),
  ('final_s_z', '/s/ – /z/ (cuối từ)', 'final', 'hiss', 'his', '/ˈhɪs/', '/ˈhɪz/'),
  ('final_s_z', '/s/ – /z/ (cuối từ)', 'final', 'since', 'sins', '/ˈsɪns/', '/ˈsɪnz/'),
  ('final_s_z', '/s/ – /z/ (cuối từ)', 'final', 'tense', 'tens', '/ˈtɛns/', '/ˈtɛnz/'),
  ('final_s_z', '/s/ – /z/ (cuối từ)', 'final', 'cease', 'seize', '/ˈsiːs/', '/ˈsiːz/'),
  ('final_s_z', '/s/ – /z/ (cuối từ)', 'final', 'fleece', 'flees', '/ˈfliːs/', '/ˈfliːz/'),
  ('final_s_z', '/s/ – /z/ (cuối từ)', 'final', 'pace', 'pays', '/ˈpeɪs/', '/ˈpeɪz/'),
  ('final_s_z', '/s/ – /z/ (cuối từ)', 'final', 'base', 'bays', '/ˈbeɪs/', '/ˈbeɪz/'),
  ('final_s_z', '/s/ – /z/ (cuối từ)', 'final', 'lace', 'lays', '/ˈleɪs/', '/ˈleɪz/'),
  ('final_s_z', '/s/ – /z/ (cuối từ)', 'final', 'trace', 'trays', '/ˈtreɪs/', '/ˈtreɪz/'),
  ('final_s_z', '/s/ – /z/ (cuối từ)', 'final', 'dose', 'doze', '/ˈdoʊs/', '/ˈdoʊz/'),
  ('final_s_z', '/s/ – /z/ (cuối từ)', 'final', 'gross', 'grows', '/ˈɡroʊs/', '/ˈɡroʊz/'),
  ('final_s_z', '/s/ – /z/ (cuối từ)', 'final', 'lice', 'lies', '/ˈlaɪs/', '/ˈlaɪz/'),
  ('final_s_z', '/s/ – /z/ (cuối từ)', 'final', 'dice', 'dies', '/ˈdaɪs/', '/ˈdaɪz/'),
  ('final_s_z', '/s/ – /z/ (cuối từ)', 'final', 'spice', 'spies', '/ˈspaɪs/', '/ˈspaɪz/'),
  ('final_s_z', '/s/ – /z/ (cuối từ)', 'final', 'fuss', 'fuzz', '/ˈfʌs/', '/ˈfʌz/'),
  ('final_s_z', '/s/ – /z/ (cuối từ)', 'final', 'course', 'cores', '/ˈkɔrs/', '/ˈkɔrz/'),
  ('final_s_z', '/s/ – /z/ (cuối từ)', 'final', 'grace', 'grays', '/ˈɡreɪs/', '/ˈɡreɪz/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'bat', 'bad', '/ˈbæt/', '/ˈbæd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'cart', 'card', '/ˈkɑrt/', '/ˈkɑrd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'write', 'ride', '/ˈraɪt/', '/ˈraɪd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'hat', 'had', '/ˈhæt/', '/ˈhæd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'bet', 'bed', '/ˈbɛt/', '/ˈbɛd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'set', 'said', '/ˈsɛt/', '/ˈsɛd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'neat', 'need', '/ˈniːt/', '/ˈniːd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'seat', 'seed', '/ˈsiːt/', '/ˈsiːd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'let', 'led', '/ˈlɛt/', '/ˈlɛd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'heart', 'hard', '/ˈhɑrt/', '/ˈhɑrd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'coat', 'code', '/ˈkoʊt/', '/ˈkoʊd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'white', 'wide', '/ˈwaɪt/', '/ˈwaɪd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'light', 'lied', '/ˈlaɪt/', '/ˈlaɪd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'site', 'side', '/ˈsaɪt/', '/ˈsaɪd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'mat', 'mad', '/ˈmæt/', '/ˈmæd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'sat', 'sad', '/ˈsæt/', '/ˈsæd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'feet', 'feed', '/ˈfiːt/', '/ˈfiːd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'but', 'bud', '/ˈbʌt/', '/ˈbʌd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'not', 'nod', '/ˈnɑt/', '/ˈnɑd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'got', 'god', '/ˈɡɑt/', '/ˈɡɑd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'hurt', 'heard', '/ˈhɜrt/', '/ˈhɜrd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'built', 'build', '/ˈbɪlt/', '/ˈbɪld/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'tent', 'tend', '/ˈtɛnt/', '/ˈtɛnd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'bent', 'bend', '/ˈbɛnt/', '/ˈbɛnd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'spent', 'spend', '/ˈspɛnt/', '/ˈspɛnd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'sent', 'send', '/ˈsɛnt/', '/ˈsɛnd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'wrote', 'road', '/ˈroʊt/', '/ˈroʊd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'height', 'hide', '/ˈhaɪt/', '/ˈhaɪd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'bright', 'bride', '/ˈbraɪt/', '/ˈbraɪd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'fate', 'fade', '/ˈfeɪt/', '/ˈfeɪd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'late', 'laid', '/ˈleɪt/', '/ˈleɪd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'great', 'grade', '/ˈɡreɪt/', '/ˈɡreɪd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'wait', 'weighed', '/ˈweɪt/', '/ˈweɪd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'plate', 'played', '/ˈpleɪt/', '/ˈpleɪd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'state', 'stayed', '/ˈsteɪt/', '/ˈsteɪd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'bit', 'bid', '/ˈbɪt/', '/ˈbɪd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'debt', 'dead', '/ˈdɛt/', '/ˈdɛd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'kit', 'kid', '/ˈkɪt/', '/ˈkɪd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'hit', 'hid', '/ˈhɪt/', '/ˈhɪd/'),
  ('final_t_d', '/t/ – /d/ (cuối từ)', 'final', 'lit', 'lid', '/ˈlɪt/', '/ˈlɪd/'),
  ('final_k_g', '/k/ – /ɡ/ (cuối từ)', 'final', 'back', 'bag', '/ˈbæk/', '/ˈbæɡ/'),
  ('final_k_g', '/k/ – /ɡ/ (cuối từ)', 'final', 'duck', 'dug', '/ˈdʌk/', '/ˈdʌɡ/'),
  ('final_k_g', '/k/ – /ɡ/ (cuối từ)', 'final', 'pick', 'pig', '/ˈpɪk/', '/ˈpɪɡ/'),
  ('final_k_g', '/k/ – /ɡ/ (cuối từ)', 'final', 'rack', 'rag', '/ˈræk/', '/ˈræɡ/'),
  ('final_k_g', '/k/ – /ɡ/ (cuối từ)', 'final', 'sack', 'sag', '/ˈsæk/', '/ˈsæɡ/'),
  ('final_k_g', '/k/ – /ɡ/ (cuối từ)', 'final', 'tack', 'tag', '/ˈtæk/', '/ˈtæɡ/'),
  ('final_k_g', '/k/ – /ɡ/ (cuối từ)', 'final', 'buck', 'bug', '/ˈbʌk/', '/ˈbʌɡ/'),
  ('final_k_g', '/k/ – /ɡ/ (cuối từ)', 'final', 'tuck', 'tug', '/ˈtʌk/', '/ˈtʌɡ/'),
  ('final_k_g', '/k/ – /ɡ/ (cuối từ)', 'final', 'pluck', 'plug', '/ˈplʌk/', '/ˈplʌɡ/'),
  ('final_k_g', '/k/ – /ɡ/ (cuối từ)', 'final', 'snack', 'snag', '/ˈsnæk/', '/ˈsnæɡ/'),
  ('final_k_g', '/k/ – /ɡ/ (cuối từ)', 'final', 'clock', 'clog', '/ˈklɑk/', '/ˈklɑɡ/'),
  ('final_k_g', '/k/ – /ɡ/ (cuối từ)', 'final', 'peck', 'peg', '/ˈpɛk/', '/ˈpɛɡ/'),
  ('final_k_g', '/k/ – /ɡ/ (cuối từ)', 'final', 'lack', 'lag', '/ˈlæk/', '/ˈlæɡ/'),
  ('final_k_g', '/k/ – /ɡ/ (cuối từ)', 'final', 'leak', 'league', '/ˈliːk/', '/ˈliːɡ/'),
  ('final_k_g', '/k/ – /ɡ/ (cuối từ)', 'final', 'frock', 'frog', '/ˈfrɑk/', '/ˈfrɑɡ/'),
  ('final_k_g', '/k/ – /ɡ/ (cuối từ)', 'final', 'muck', 'mug', '/ˈmʌk/', '/ˈmʌɡ/'),
  ('final_k_g', '/k/ – /ɡ/ (cuối từ)', 'final', 'wick', 'wig', '/ˈwɪk/', '/ˈwɪɡ/'),
  ('final_k_g', '/k/ – /ɡ/ (cuối từ)', 'final', 'luck', 'lug', '/ˈlʌk/', '/ˈlʌɡ/'),
  ('final_k_g', '/k/ – /ɡ/ (cuối từ)', 'final', 'stack', 'stag', '/ˈstæk/', '/ˈstæɡ/'),
  ('final_k_g', '/k/ – /ɡ/ (cuối từ)', 'final', 'knack', 'nag', '/ˈnæk/', '/ˈnæɡ/'),
  ('final_k_g', '/k/ – /ɡ/ (cuối từ)', 'final', 'jock', 'jog', '/ˈdʒɑk/', '/ˈdʒɑɡ/'),
  ('final_k_g', '/k/ – /ɡ/ (cuối từ)', 'final', 'hack', 'hag', '/ˈhæk/', '/ˈhæɡ/'),
  ('final_k_g', '/k/ – /ɡ/ (cuối từ)', 'final', 'puck', 'pug', '/ˈpʌk/', '/ˈpʌɡ/'),
  ('final_p_b', '/p/ – /b/ (cuối từ)', 'final', 'cap', 'cab', '/ˈkæp/', '/ˈkæb/'),
  ('final_p_b', '/p/ – /b/ (cuối từ)', 'final', 'rope', 'robe', '/ˈroʊp/', '/ˈroʊb/'),
  ('final_p_b', '/p/ – /b/ (cuối từ)', 'final', 'tap', 'tab', '/ˈtæp/', '/ˈtæb/'),
  ('final_p_b', '/p/ – /b/ (cuối từ)', 'final', 'lap', 'lab', '/ˈlæp/', '/ˈlæb/'),
  ('final_p_b', '/p/ – /b/ (cuối từ)', 'final', 'cup', 'cub', '/ˈkʌp/', '/ˈkʌb/'),
  ('final_p_b', '/p/ – /b/ (cuối từ)', 'final', 'mop', 'mob', '/ˈmɑp/', '/ˈmɑb/'),
  ('final_p_b', '/p/ – /b/ (cuối từ)', 'final', 'rip', 'rib', '/ˈrɪp/', '/ˈrɪb/'),
  ('final_p_b', '/p/ – /b/ (cuối từ)', 'final', 'pup', 'pub', '/ˈpʌp/', '/ˈpʌb/'),
  ('final_p_b', '/p/ – /b/ (cuối từ)', 'final', 'slap', 'slab', '/ˈslæp/', '/ˈslæb/'),
  ('final_p_b', '/p/ – /b/ (cuối từ)', 'final', 'gap', 'gab', '/ˈɡæp/', '/ˈɡæb/'),
  ('final_p_b', '/p/ – /b/ (cuối từ)', 'final', 'flap', 'flab', '/ˈflæp/', '/ˈflæb/'),
  ('final_p_b', '/p/ – /b/ (cuối từ)', 'final', 'cop', 'cob', '/ˈkɑp/', '/ˈkɑb/'),
  ('final_p_b', '/p/ – /b/ (cuối từ)', 'final', 'hop', 'hob', '/ˈhɑp/', '/ˈhɑb/'),
  ('final_p_b', '/p/ – /b/ (cuối từ)', 'final', 'nip', 'nib', '/ˈnɪp/', '/ˈnɪb/'),
  ('final_p_b', '/p/ – /b/ (cuối từ)', 'final', 'swap', 'swab', '/ˈswɑp/', '/ˈswɑb/'),
  ('final_p_b', '/p/ – /b/ (cuối từ)', 'final', 'sup', 'sub', '/ˈsʌp/', '/ˈsʌb/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'cat', 'cats', '/ˈkæt/', '/ˈkæts/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'play', 'plays', '/ˈpleɪ/', '/ˈpleɪz/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'book', 'books', '/ˈbʊk/', '/ˈbʊks/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'car', 'cars', '/ˈkɑr/', '/ˈkɑrz/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'bag', 'bags', '/ˈbæɡ/', '/ˈbæɡz/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'cup', 'cups', '/ˈkʌp/', '/ˈkʌps/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'day', 'days', '/ˈdeɪ/', '/ˈdeɪz/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'key', 'keys', '/ˈkiː/', '/ˈkiːz/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'tree', 'trees', '/ˈtriː/', '/ˈtriːz/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'bird', 'birds', '/ˈbɜrd/', '/ˈbɜrdz/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'hand', 'hands', '/ˈhænd/', '/ˈhændz/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'friend', 'friends', '/ˈfrɛnd/', '/ˈfrɛndz/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'road', 'roads', '/ˈroʊd/', '/ˈroʊdz/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'shop', 'shops', '/ˈʃɑp/', '/ˈʃɑps/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'map', 'maps', '/ˈmæp/', '/ˈmæps/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'desk', 'desks', '/ˈdɛsk/', '/ˈdɛsks/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'street', 'streets', '/ˈstriːt/', '/ˈstriːts/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'name', 'names', '/ˈneɪm/', '/ˈneɪmz/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'song', 'songs', '/ˈsɔŋ/', '/ˈsɔŋz/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'girl', 'girls', '/ˈɡɜrl/', '/ˈɡɜrlz/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'boy', 'boys', '/ˈbɔɪ/', '/ˈbɔɪz/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'shoe', 'shoes', '/ˈʃuː/', '/ˈʃuːz/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'room', 'rooms', '/ˈruːm/', '/ˈruːmz/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'pen', 'pens', '/ˈpɛn/', '/ˈpɛnz/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'phone', 'phones', '/ˈfoʊn/', '/ˈfoʊnz/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'run', 'runs', '/ˈrʌn/', '/ˈrʌnz/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'sing', 'sings', '/ˈsɪŋ/', '/ˈsɪŋz/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'eat', 'eats', '/ˈiːt/', '/ˈiːts/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'drink', 'drinks', '/ˈdrɪŋk/', '/ˈdrɪŋks/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'stop', 'stops', '/ˈstɑp/', '/ˈstɑps/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'like', 'likes', '/ˈlaɪk/', '/ˈlaɪks/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'need', 'needs', '/ˈniːd/', '/ˈniːdz/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'see', 'sees', '/ˈsiː/', '/ˈsiːz/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'make', 'makes', '/ˈmeɪk/', '/ˈmeɪks/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'help', 'helps', '/ˈhɛlp/', '/ˈhɛlps/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'work', 'works', '/ˈwɜrk/', '/ˈwɜrks/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'call', 'calls', '/ˈkɔl/', '/ˈkɔlz/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'come', 'comes', '/ˈkʌm/', '/ˈkʌmz/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'week', 'weeks', '/ˈwiːk/', '/ˈwiːks/'),
  ('ending_s', 'đuôi -s /s/ /z/', 'ending', 'sock', 'socks', '/ˈsɑk/', '/ˈsɑks/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'walk', 'walked', '/ˈwɔk/', '/ˈwɔkt/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'play', 'played', '/ˈpleɪ/', '/ˈpleɪd/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'miss', 'missed', '/ˈmɪs/', '/ˈmɪst/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'stop', 'stopped', '/ˈstɑp/', '/ˈstɑpt/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'work', 'worked', '/ˈwɜrk/', '/ˈwɜrkt/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'call', 'called', '/ˈkɔl/', '/ˈkɔld/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'open', 'opened', '/ˈoʊpən/', '/ˈoʊpənd/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'clean', 'cleaned', '/ˈkliːn/', '/ˈkliːnd/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'cook', 'cooked', '/ˈkʊk/', '/ˈkʊkt/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'help', 'helped', '/ˈhɛlp/', '/ˈhɛlpt/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'like', 'liked', '/ˈlaɪk/', '/ˈlaɪkt/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'look', 'looked', '/ˈlʊk/', '/ˈlʊkt/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'watch', 'watched', '/ˈwɑtʃ/', '/ˈwɑtʃt/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'wash', 'washed', '/ˈwɑʃ/', '/ˈwɑʃt/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'jump', 'jumped', '/ˈdʒʌmp/', '/ˈdʒʌmpt/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'kiss', 'kissed', '/ˈkɪs/', '/ˈkɪst/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'laugh', 'laughed', '/ˈlæf/', '/ˈlæft/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'pass', 'passed', '/ˈpæs/', '/ˈpæst/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'stay', 'stayed', '/ˈsteɪ/', '/ˈsteɪd/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'try', 'tried', '/ˈtraɪ/', '/ˈtraɪd/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'cry', 'cried', '/ˈkraɪ/', '/ˈkraɪd/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'love', 'loved', '/ˈlʌv/', '/ˈlʌvd/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'move', 'moved', '/ˈmuːv/', '/ˈmuːvd/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'change', 'changed', '/ˈtʃeɪndʒ/', '/ˈtʃeɪndʒd/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'agree', 'agreed', '/əˈɡriː/', '/əˈɡriːd/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'rain', 'rained', '/ˈreɪn/', '/ˈreɪnd/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'turn', 'turned', '/ˈtɜrn/', '/ˈtɜrnd/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'listen', 'listened', '/ˈlɪsən/', '/ˈlɪsənd/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'answer', 'answered', '/ˈænsər/', '/ˈænsərd/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'show', 'showed', '/ˈʃoʊ/', '/ˈʃoʊd/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'fix', 'fixed', '/ˈfɪks/', '/ˈfɪkst/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'finish', 'finished', '/ˈfɪnɪʃ/', '/ˈfɪnɪʃt/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'ask', 'asked', '/ˈæsk/', '/ˈæskt/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'dance', 'danced', '/ˈdæns/', '/ˈdænst/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'hope', 'hoped', '/ˈhoʊp/', '/ˈhoʊpt/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'smile', 'smiled', '/ˈsmaɪl/', '/ˈsmaɪld/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'learn', 'learned', '/ˈlɜrn/', '/ˈlɜrnd/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'plan', 'planned', '/ˈplæn/', '/ˈplænd/'),
  ('ending_ed', 'đuôi -ed /t/ /d/', 'ending', 'relax', 'relaxed', '/rɪˈlæks/', '/rɪˈlækst/');

-- config_json: { contrasts, per_group, scoring }
INSERT INTO roadmap_item_tests (item_key, tool, list_code, config_json) VALUES
  ('nghe-01', 'T8', NULL, '{"contrasts":["ɪ_iː","æ_e","æ_ʌ","e_ʌ","ʊ_uː"],"per_group":10,"scoring":"min_group"}'),
  ('nghe-02', 'T8', NULL, '{"contrasts":["θ_s","ð_d","v_w","ʃ_s","tʃ_dʒ","r_l"],"per_group":10,"scoring":"min_group"}'),
  ('nghe-03', 'T8', NULL, '{"contrasts":["final_s_z","final_t_d","final_k_g","final_p_b","ending_s","ending_ed"],"per_group":6,"scoring":"overall"}');
