-- Thư viện bộ từ có sẵn (preset decks): bộ NGSL / AWL chia theo level, mỗi bộ
-- ≤ 30 từ, nội dung soạn sẵn (nghĩa, 3 ví dụ en+vi, collocation).
--
-- Ba bảng dưới KHÔNG có user_id: nội dung tham chiếu dùng chung, giống
-- word_list_entries. User "lấy bộ về" = CHÉP các từ đã chọn thành
-- flashcards của user; bộ gốc không bao giờ bị sửa.
--
-- Sinh bởi scripts/gen-preset-decks-seed.mjs từ content/preset-decks/.
-- IPA không lưu ở đây: đọc từ word_glossary (Oxford US) lúc hiển thị / chép.

CREATE TABLE IF NOT EXISTS preset_deck_levels (
  code TEXT PRIMARY KEY,
  list_code TEXT NOT NULL,
  label TEXT NOT NULL,
  description TEXT,
  position INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS preset_decks (
  code TEXT PRIMARY KEY,
  level_code TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  color TEXT NOT NULL,
  icon TEXT,
  position INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (level_code) REFERENCES preset_deck_levels(code)
);

CREATE INDEX IF NOT EXISTS idx_preset_decks_level
  ON preset_decks(level_code, position);

CREATE TABLE IF NOT EXISTS preset_deck_cards (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  deck_code TEXT NOT NULL,
  position INTEGER NOT NULL DEFAULT 0,
  english TEXT NOT NULL,
  vietnamese TEXT NOT NULL,
  part_of_speech TEXT,
  examples TEXT NOT NULL DEFAULT '[]',
  collocations TEXT NOT NULL DEFAULT '[]',
  notes TEXT,
  UNIQUE (deck_code, english),
  FOREIGN KEY (deck_code) REFERENCES preset_decks(code)
);

CREATE INDEX IF NOT EXISTS idx_preset_deck_cards_deck
  ON preset_deck_cards(deck_code, position);

-- Levels (tất cả, INSERT OR IGNORE)
INSERT OR IGNORE INTO preset_deck_levels (code, list_code, label, description, position) VALUES
  ('ngsl-1', 'ngsl', 'Từ thông dụng 1–500', 'New General Service List, thứ hạng 1–500', 1),
  ('ngsl-2', 'ngsl', 'Từ thông dụng 501–1.000', 'New General Service List, thứ hạng 501–1.000', 2),
  ('ngsl-3', 'ngsl', 'Từ thông dụng 1.001–1.500', 'New General Service List, thứ hạng 1.001–1.500', 3),
  ('ngsl-4', 'ngsl', 'Từ thông dụng 1.501–2.000', 'New General Service List, thứ hạng 1.501–2.000', 4),
  ('ngsl-5', 'ngsl', 'Từ thông dụng 2.001–2.500', 'New General Service List, thứ hạng 2.001–2.500', 5),
  ('ngsl-6', 'ngsl', 'Từ thông dụng 2.501–2.809', 'New General Service List, thứ hạng 2.501–2.809', 6),
  ('awl-1', 'awl', 'Học thuật · Sublist 1', 'Academic Word List, sublist 1', 101),
  ('awl-2', 'awl', 'Học thuật · Sublist 2', 'Academic Word List, sublist 2', 102),
  ('awl-3', 'awl', 'Học thuật · Sublist 3', 'Academic Word List, sublist 3', 103),
  ('awl-4', 'awl', 'Học thuật · Sublist 4', 'Academic Word List, sublist 4', 104),
  ('awl-5', 'awl', 'Học thuật · Sublist 5', 'Academic Word List, sublist 5', 105),
  ('awl-6', 'awl', 'Học thuật · Sublist 6', 'Academic Word List, sublist 6', 106),
  ('awl-7', 'awl', 'Học thuật · Sublist 7', 'Academic Word List, sublist 7', 107),
  ('awl-8', 'awl', 'Học thuật · Sublist 8', 'Academic Word List, sublist 8', 108),
  ('awl-9', 'awl', 'Học thuật · Sublist 9', 'Academic Word List, sublist 9', 109),
  ('awl-10', 'awl', 'Học thuật · Sublist 10', 'Academic Word List, sublist 10', 110);

-- ngsl-1-01: Thông dụng 1–500 · Bộ 1 (30 từ)
INSERT INTO preset_decks (code, level_code, name, description, color, icon, position) VALUES ('ngsl-1-01', 'ngsl-1', 'Thông dụng 1–500 · Bộ 1', 'New General Service List, thứ hạng 1–500', '#3da9fc', 'BookOpen', 1);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-01', 1, 'say', 'nói; cho biết', 'verb', '[{"en":"What did she say when you told her the news?","vi":"Cô ấy đã nói gì khi bạn báo tin cho cô ấy?"},{"en":"My doctor said I should drink more water.","vi":"Bác sĩ nói tôi nên uống nhiều nước hơn."},{"en":"The sign says the museum is closed on Mondays.","vi":"Biển báo cho biết bảo tàng đóng cửa vào thứ Hai."}]', '[{"phrase":"say goodbye"},{"phrase":"say sorry"},{"phrase":"say something"},{"phrase":"say no"}]', 'say – said – said');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-01', 2, 'go', 'đi; diễn ra', 'verb', '[{"en":"We usually go to the beach on weekends.","vi":"Chúng tôi thường đi biển vào cuối tuần."},{"en":"She went home early because she felt tired.","vi":"Cô ấy về nhà sớm vì cảm thấy mệt."},{"en":"How did your job interview go yesterday?","vi":"Buổi phỏng vấn xin việc hôm qua của bạn diễn ra thế nào?"}]', '[{"phrase":"go home"},{"phrase":"go to bed"},{"phrase":"go shopping"},{"phrase":"go to school"}]', 'go – went – gone');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-01', 3, 'know', 'biết; quen biết', 'verb', '[{"en":"Do you know where the nearest bus stop is?","vi":"Bạn có biết trạm xe buýt gần nhất ở đâu không?"},{"en":"She didn''t know the answer, so she asked her teacher.","vi":"Cô ấy không biết câu trả lời nên đã hỏi giáo viên."},{"en":"I have known my best friend since elementary school.","vi":"Tôi quen người bạn thân nhất của mình từ hồi tiểu học."}]', '[{"phrase":"know the answer"},{"phrase":"get to know"},{"phrase":"let me know"}]', 'know – knew – known');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-01', 4, 'more', 'nhiều hơn; thêm', 'determiner', '[{"en":"We need more time to finish the project.","vi":"Chúng tôi cần thêm thời gian để hoàn thành dự án."},{"en":"Could I have some more rice, please?","vi":"Cho tôi xin thêm một chút cơm được không?"},{"en":"More people are working from home these days.","vi":"Dạo này có nhiều người làm việc tại nhà hơn."}]', '[{"phrase":"more time"},{"phrase":"more money"},{"phrase":"more than"},{"phrase":"once more"}]', 'so sánh hơn của many/much');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-01', 5, 'get', 'nhận được; lấy; trở nên', 'verb', '[{"en":"I got a message from my sister this morning.","vi":"Sáng nay tôi nhận được tin nhắn từ chị gái."},{"en":"Can you get me a glass of water?","vi":"Bạn lấy giúp tôi một cốc nước được không?"},{"en":"It gets dark very early in the winter.","vi":"Vào mùa đông, trời tối rất sớm."}]', '[{"phrase":"get a job"},{"phrase":"get home"},{"phrase":"get better"},{"phrase":"get ready"}]', 'get – got – got (Mỹ: gotten)');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-01', 6, 'like', 'thích', 'verb', '[{"en":"I like reading books before I go to bed.","vi":"Tôi thích đọc sách trước khi đi ngủ."},{"en":"My kids don''t like vegetables very much.","vi":"Bọn trẻ nhà tôi không thích ăn rau lắm."},{"en":"She really likes her new apartment near the park.","vi":"Cô ấy rất thích căn hộ mới gần công viên."}]', '[{"phrase":"really like"},{"phrase":"would like"},{"phrase":"like best"}]', 'would like = muốn (lịch sự)');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-01', 7, 'think', 'nghĩ; cho rằng', 'verb', '[{"en":"I think it''s going to rain this afternoon.","vi":"Tôi nghĩ chiều nay trời sẽ mưa."},{"en":"What do you think of the new teacher?","vi":"Bạn nghĩ gì về giáo viên mới?"},{"en":"He is thinking about changing jobs next year.","vi":"Anh ấy đang nghĩ đến chuyện đổi việc vào năm sau."}]', '[{"phrase":"think about"},{"phrase":"think of"},{"phrase":"think so"},{"phrase":"think carefully"}]', 'think – thought – thought');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-01', 8, 'make', 'làm; tạo ra; khiến', 'verb', '[{"en":"My mom is making dinner in the kitchen.","vi":"Mẹ tôi đang làm bữa tối trong bếp."},{"en":"This company makes furniture for schools and offices.","vi":"Công ty này sản xuất đồ nội thất cho trường học và văn phòng."},{"en":"That sad movie made everyone in the room cry.","vi":"Bộ phim buồn đó khiến mọi người trong phòng đều khóc."}]', '[{"phrase":"make a mistake"},{"phrase":"make a decision"},{"phrase":"make money"},{"phrase":"make friends"}]', 'make – made – made');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-01', 9, 'time', 'thời gian; lần; giờ', 'noun', '[{"en":"I don''t have much free time during the week.","vi":"Trong tuần tôi không có nhiều thời gian rảnh."},{"en":"I''ve called him three times, but he isn''t answering.","vi":"Tôi đã gọi cho anh ấy ba lần nhưng anh ấy không nghe máy."},{"en":"What time does the next train leave?","vi":"Chuyến tàu tiếp theo khởi hành lúc mấy giờ?"}]', '[{"phrase":"free time"},{"phrase":"spend time"},{"phrase":"on time"},{"phrase":"have a good time"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-01', 10, 'see', 'nhìn thấy; gặp; hiểu', 'verb', '[{"en":"Did you see the rainbow after the rain?","vi":"Bạn có thấy cầu vồng sau cơn mưa không?"},{"en":"I''m going to see my grandparents this weekend.","vi":"Cuối tuần này tôi sẽ đi thăm ông bà."},{"en":"I see what you mean now, thank you.","vi":"Giờ thì tôi hiểu ý bạn rồi, cảm ơn nhé."}]', '[{"phrase":"see a doctor"},{"phrase":"see a movie"},{"phrase":"see you later"}]', 'see – saw – seen');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-01', 11, 'good', 'tốt; giỏi; hay', 'adjective', '[{"en":"Eating fruit every day is good for your health.","vi":"Ăn trái cây mỗi ngày tốt cho sức khỏe."},{"en":"She is very good at math and science.","vi":"Cô ấy rất giỏi toán và khoa học."},{"en":"You should watch that movie because it''s really good.","vi":"Bạn nên xem bộ phim đó vì nó rất hay."}]', '[{"phrase":"good at"},{"phrase":"good for"},{"phrase":"good idea"},{"phrase":"good news"}]', 'good – better – best');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-01', 12, 'people', 'người; mọi người', 'noun', '[{"en":"Many people take the bus to work in this city.","vi":"Ở thành phố này, nhiều người đi làm bằng xe buýt."},{"en":"How many people are coming to your party?","vi":"Có bao nhiêu người sẽ đến bữa tiệc của bạn?"},{"en":"People are usually very friendly in small towns.","vi":"Ở các thị trấn nhỏ, mọi người thường rất thân thiện."}]', '[{"phrase":"most people"},{"phrase":"young people"},{"phrase":"local people"},{"phrase":"many people"}]', 'số nhiều của person');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-01', 13, 'year', 'năm; tuổi', 'noun', '[{"en":"We moved to this city three years ago.","vi":"Chúng tôi chuyển đến thành phố này ba năm trước."},{"en":"She travels abroad at least once a year.","vi":"Cô ấy đi du lịch nước ngoài ít nhất mỗi năm một lần."},{"en":"My son will be seven years old next month.","vi":"Tháng sau con trai tôi sẽ tròn bảy tuổi."}]', '[{"phrase":"last year"},{"phrase":"next year"},{"phrase":"every year"},{"phrase":"years old"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-01', 14, 'take', 'lấy; mang theo; mất (thời gian)', 'verb', '[{"en":"She took a book from the shelf and started reading.","vi":"Cô ấy lấy một cuốn sách trên kệ và bắt đầu đọc."},{"en":"Don''t forget to take an umbrella with you.","vi":"Đừng quên mang theo ô nhé."},{"en":"It takes about twenty minutes to walk to school.","vi":"Đi bộ đến trường mất khoảng hai mươi phút."}]', '[{"phrase":"take a photo"},{"phrase":"take a break"},{"phrase":"take the bus"},{"phrase":"take time"}]', 'take – took – taken');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-01', 15, 'well', 'tốt; giỏi; kỹ', 'adverb', '[{"en":"I didn''t sleep well last night because of the noise.","vi":"Đêm qua tôi ngủ không ngon vì tiếng ồn."},{"en":"My brother can speak English and French very well.","vi":"Anh trai tôi nói tiếng Anh và tiếng Pháp rất giỏi."},{"en":"Shake the bottle well before you use it.","vi":"Lắc kỹ chai trước khi dùng."}]', '[{"phrase":"very well"},{"phrase":"sleep well"},{"phrase":"do well"}]', 'good (tính từ) ≠ well (trạng từ)');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-01', 16, 'because', 'vì; bởi vì', 'conjunction', '[{"en":"I stayed home because I had a bad cold.","vi":"Tôi ở nhà vì bị cảm nặng."},{"en":"We took a taxi because it was raining heavily.","vi":"Chúng tôi đi taxi vì trời mưa to."},{"en":"Because the store was closed, we went somewhere else.","vi":"Vì cửa hàng đã đóng cửa nên chúng tôi đi chỗ khác."}]', '[{"phrase":"because of"},{"phrase":"just because"},{"phrase":"only because"}]', 'because + mệnh đề; because of + danh từ');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-01', 17, 'come', 'đến; về', 'verb', '[{"en":"Can you come to my birthday party on Saturday?","vi":"Thứ Bảy bạn đến dự tiệc sinh nhật của tôi được không?"},{"en":"My father usually comes home from work at six.","vi":"Bố tôi thường đi làm về lúc sáu giờ."},{"en":"Where does your new roommate come from?","vi":"Bạn cùng phòng mới của bạn đến từ đâu?"}]', '[{"phrase":"come home"},{"phrase":"come back"},{"phrase":"come in"},{"phrase":"come from"}]', 'come – came – come');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-01', 18, 'work', 'làm việc; hoạt động', 'verb', '[{"en":"My mother works at a hospital in the city.","vi":"Mẹ tôi làm việc tại một bệnh viện trong thành phố."},{"en":"I have to work late tonight to finish this report.","vi":"Tối nay tôi phải làm việc muộn để hoàn thành bản báo cáo này."},{"en":"The printer in our office isn''t working again.","vi":"Máy in trong văn phòng chúng tôi lại không hoạt động rồi."}]', '[{"phrase":"work hard"},{"phrase":"work late"},{"phrase":"work from home"},{"phrase":"work together"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-01', 19, 'use', 'sử dụng; dùng', 'verb', '[{"en":"Can I use your phone for a minute?","vi":"Cho tôi dùng điện thoại của bạn một lát được không?"},{"en":"We use this room for meetings and training.","vi":"Chúng tôi dùng phòng này để họp và đào tạo."},{"en":"She used a knife to open the box.","vi":"Cô ấy dùng dao để mở chiếc hộp."}]', '[{"phrase":"use a computer"},{"phrase":"use the bathroom"},{"phrase":"easy to use"}]', 'used to + V = đã từng (khác với use)');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-01', 20, 'look', 'nhìn; trông', 'verb', '[{"en":"Look at the beautiful sunset over the sea.","vi":"Nhìn hoàng hôn tuyệt đẹp trên biển kìa."},{"en":"He looked out of the window and saw the snow.","vi":"Anh ấy nhìn ra ngoài cửa sổ và thấy tuyết."},{"en":"You look very tired after your long trip.","vi":"Trông bạn rất mệt sau chuyến đi dài."}]', '[{"phrase":"look at"},{"phrase":"look for"},{"phrase":"look after"},{"phrase":"look happy"}]', 'look at: nhìn vào; look for: tìm; look after: chăm sóc');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-01', 21, 'want', 'muốn', 'verb', '[{"en":"I want to learn how to cook Italian food.","vi":"Tôi muốn học cách nấu món Ý."},{"en":"What do you want for your birthday?","vi":"Bạn muốn được tặng gì vào dịp sinh nhật?"},{"en":"My parents wanted me to become a doctor.","vi":"Bố mẹ tôi đã muốn tôi trở thành bác sĩ."}]', '[{"phrase":"really want"},{"phrase":"want to know"},{"phrase":"want to go"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-01', 22, 'give', 'đưa; cho; tặng', 'verb', '[{"en":"Please give this letter to your teacher.","vi":"Em hãy đưa lá thư này cho giáo viên của em nhé."},{"en":"Could you give me some advice about buying a car?","vi":"Bạn có thể cho tôi vài lời khuyên về việc mua xe không?"},{"en":"My aunt gave me a watch for my birthday.","vi":"Dì tặng tôi một chiếc đồng hồ nhân dịp sinh nhật."}]', '[{"phrase":"give advice"},{"phrase":"give a speech"},{"phrase":"give up"}]', 'give – gave – given');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-01', 23, 'first', 'đầu tiên; thứ nhất', 'adjective', '[{"en":"I still remember my first day at school.","vi":"Tôi vẫn nhớ ngày đầu tiên đi học."},{"en":"The first train leaves at five in the morning.","vi":"Chuyến tàu đầu tiên khởi hành lúc năm giờ sáng."},{"en":"Take the first street on the left after the bank.","vi":"Rẽ vào con phố đầu tiên bên trái sau ngân hàng."}]', '[{"phrase":"first time"},{"phrase":"first day"},{"phrase":"first step"},{"phrase":"at first"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-01', 24, 'new', 'mới', 'adjective', '[{"en":"I bought a new laptop for my studies.","vi":"Tôi mua một chiếc máy tính xách tay mới để học."},{"en":"Our new neighbors are very friendly and helpful.","vi":"Hàng xóm mới của chúng tôi rất thân thiện và hay giúp đỡ."},{"en":"Is it hard to make new friends in a big city?","vi":"Kết bạn mới ở thành phố lớn có khó không?"}]', '[{"phrase":"new job"},{"phrase":"brand new"},{"phrase":"new friends"},{"phrase":"something new"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-01', 25, 'way', 'cách; đường', 'noun', '[{"en":"What is the best way to learn English?","vi":"Cách tốt nhất để học tiếng Anh là gì?"},{"en":"Excuse me, could you tell me the way to the station?","vi":"Xin lỗi, bạn có thể chỉ giúp tôi đường đến nhà ga không?"},{"en":"I bought some bread on my way home.","vi":"Tôi mua ít bánh mì trên đường về nhà."}]', '[{"phrase":"the best way"},{"phrase":"on the way"},{"phrase":"a long way"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-01', 26, 'find', 'tìm thấy; thấy', 'verb', '[{"en":"I can''t find my car keys anywhere this morning.","vi":"Sáng nay tôi tìm khắp nơi mà không thấy chìa khóa xe."},{"en":"She finally found a job at a local bank.","vi":"Cuối cùng cô ấy cũng tìm được việc ở một ngân hàng địa phương."},{"en":"Most students find this exercise quite difficult.","vi":"Hầu hết học sinh thấy bài tập này khá khó."}]', '[{"phrase":"find a job"},{"phrase":"find out"},{"phrase":"find the answer"},{"phrase":"hard to find"}]', 'find – found – found');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-01', 27, 'day', 'ngày; ban ngày', 'noun', '[{"en":"I drink two cups of coffee a day.","vi":"Tôi uống hai tách cà phê mỗi ngày."},{"en":"We spent the whole day at the beach.","vi":"Chúng tôi ở bãi biển cả ngày."},{"en":"My father works during the day and studies at night.","vi":"Bố tôi làm việc ban ngày và đi học vào buổi tối."}]', '[{"phrase":"every day"},{"phrase":"all day"},{"phrase":"the next day"},{"phrase":"during the day"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-01', 28, 'thing', 'đồ vật; điều; việc', 'noun', '[{"en":"Put your things in the bag before we leave.","vi":"Cất đồ của bạn vào túi trước khi chúng ta đi nhé."},{"en":"The most important thing is your health.","vi":"Điều quan trọng nhất là sức khỏe của bạn."},{"en":"I have a lot of things to do today.","vi":"Hôm nay tôi có rất nhiều việc phải làm."}]', '[{"phrase":"the only thing"},{"phrase":"the same thing"},{"phrase":"the most important thing"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-01', 29, 'need', 'cần', 'verb', '[{"en":"I need to buy some milk on the way home.","vi":"Tôi cần mua ít sữa trên đường về nhà."},{"en":"Do you need any help with those bags?","vi":"Bạn có cần giúp mang mấy cái túi đó không?"},{"en":"Plants need water and sunlight to grow.","vi":"Cây cần nước và ánh nắng để phát triển."}]', '[{"phrase":"need help"},{"phrase":"need to know"},{"phrase":"really need"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-01', 30, 'right', 'đúng; bên phải', 'adjective', '[{"en":"You''re right, the meeting starts at ten, not nine.","vi":"Bạn nói đúng, cuộc họp bắt đầu lúc mười giờ chứ không phải chín giờ."},{"en":"Is this the right bus for the city center?","vi":"Đây có đúng là xe buýt đi vào trung tâm thành phố không?"},{"en":"She broke her right arm while playing basketball.","vi":"Cô ấy bị gãy tay phải khi chơi bóng rổ."}]', '[{"phrase":"the right answer"},{"phrase":"right hand"},{"phrase":"right side"},{"phrase":"exactly right"}]', NULL);

-- ngsl-1-02: Thông dụng 1–500 · Bộ 2 (30 từ)
INSERT INTO preset_decks (code, level_code, name, description, color, icon, position) VALUES ('ngsl-1-02', 'ngsl-1', 'Thông dụng 1–500 · Bộ 2', 'New General Service List, thứ hạng 1–500', '#3da9fc', 'BookOpen', 2);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-02', 1, 'back', 'trở lại, quay lại; về phía sau', 'adverb', '[{"en":"I''ll be back in about ten minutes.","vi":"Khoảng mười phút nữa tôi sẽ quay lại."},{"en":"She looked back and waved goodbye to us.","vi":"Cô ấy ngoảnh lại và vẫy tay chào tạm biệt chúng tôi."},{"en":"What time did you come back last night?","vi":"Tối qua mấy giờ bạn mới quay về?"}]', '[{"phrase":"come back"},{"phrase":"go back"},{"phrase":"look back"},{"phrase":"give back"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-02', 2, 'mean', 'có nghĩa là; ý muốn nói; cố ý, định', 'verb', '[{"en":"What does this word mean in Vietnamese?","vi":"Từ này trong tiếng Việt có nghĩa là gì?"},{"en":"I know what you mean, but I don''t agree.","vi":"Tôi hiểu ý bạn, nhưng tôi không đồng ý."},{"en":"Sorry, I didn''t mean to wake you up.","vi":"Xin lỗi, tôi không cố ý đánh thức bạn."}]', '[{"phrase":"what do you mean"},{"phrase":"mean to do something"},{"phrase":"mean a lot to someone"}]', 'mean – meant – meant');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-02', 3, 'even', 'ngay cả, thậm chí; còn (hơn nữa)', 'adverb', '[{"en":"Even my little brother can use this phone.","vi":"Ngay cả em trai tôi cũng dùng được chiếc điện thoại này."},{"en":"He didn''t even say goodbye before he left.","vi":"Anh ấy thậm chí còn không chào tạm biệt trước khi đi."},{"en":"The second test was even harder than the first one.","vi":"Bài kiểm tra thứ hai còn khó hơn bài đầu tiên."}]', '[{"phrase":"even if"},{"phrase":"even though"},{"phrase":"even better"},{"phrase":"not even"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-02', 4, 'last', 'cuối cùng; trước, vừa qua', 'adjective', '[{"en":"This is the last bus to the city tonight.","vi":"Đây là chuyến xe buýt cuối cùng vào thành phố tối nay."},{"en":"We went to the beach last weekend.","vi":"Cuối tuần trước chúng tôi đã đi biển."},{"en":"When was the last time you saw a doctor?","vi":"Lần cuối bạn đi khám bác sĩ là khi nào?"}]', '[{"phrase":"last week"},{"phrase":"last night"},{"phrase":"the last time"},{"phrase":"the last minute"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-02', 5, 'child', 'đứa trẻ, trẻ em; con (cái)', 'noun', '[{"en":"Every child in the class got a small gift.","vi":"Mọi đứa trẻ trong lớp đều nhận được một món quà nhỏ."},{"en":"They have three children, two boys and a girl.","vi":"Họ có ba người con, hai trai một gái."},{"en":"As a child, I spent every summer at my grandmother''s house.","vi":"Hồi nhỏ, mùa hè nào tôi cũng ở nhà bà."}]', '[{"phrase":"young children"},{"phrase":"an only child"},{"phrase":"have children"},{"phrase":"raise children"}]', 'số nhiều: children');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-02', 6, 'tell', 'nói (cho ai biết); kể; bảo', 'verb', '[{"en":"Can you tell me where the train station is?","vi":"Bạn có thể cho tôi biết nhà ga ở đâu không?"},{"en":"My grandfather told us a funny story last night.","vi":"Tối qua ông tôi kể cho chúng tôi nghe một câu chuyện vui."},{"en":"The teacher told the students to turn off their phones.","vi":"Cô giáo bảo học sinh tắt điện thoại."}]', '[{"phrase":"tell a story"},{"phrase":"tell the truth"},{"phrase":"tell a lie"},{"phrase":"tell someone to do something"}]', 'tell – told – told');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-02', 7, 'really', 'thật sự, thực sự; rất', 'adverb', '[{"en":"Do you really want to quit your job?","vi":"Bạn thật sự muốn nghỉ việc à?"},{"en":"We had a really good time at the party.","vi":"Chúng tôi đã rất vui ở bữa tiệc."},{"en":"I''m really sorry that I forgot your birthday.","vi":"Tôi thực sự xin lỗi vì đã quên sinh nhật của bạn."}]', '[{"phrase":"really good"},{"phrase":"really want"},{"phrase":"really sorry"},{"phrase":"not really"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-02', 8, 'call', 'gọi điện (cho); gọi, gọi là', 'verb', '[{"en":"I''ll call you when I get home.","vi":"Khi về đến nhà tôi sẽ gọi cho bạn."},{"en":"Can you call me back in an hour?","vi":"Một tiếng nữa bạn gọi lại cho tôi được không?"},{"en":"What do you call this dish in English?","vi":"Món này tiếng Anh gọi là gì?"}]', '[{"phrase":"call someone back"},{"phrase":"call a taxi"},{"phrase":"call the police"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-02', 9, 'before', 'trước; trước khi; trước đây', 'preposition', '[{"en":"We arrived just before the movie started.","vi":"Chúng tôi đến ngay trước khi phim bắt đầu."},{"en":"Always wash your hands before you eat.","vi":"Hãy luôn rửa tay trước khi ăn."},{"en":"I have never seen this movie before.","vi":"Tôi chưa bao giờ xem bộ phim này trước đây."}]', '[{"phrase":"just before"},{"phrase":"the day before"},{"phrase":"before long"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-02', 10, 'company', 'công ty; sự bầu bạn, sự có mặt (của ai)', 'noun', '[{"en":"My sister works for a small software company.","vi":"Chị tôi làm việc cho một công ty phần mềm nhỏ."},{"en":"The company hired twenty new workers this year.","vi":"Năm nay công ty đã tuyển hai mươi nhân viên mới."},{"en":"I enjoy her company because she always makes me laugh.","vi":"Tôi thích ở bên cô ấy vì cô ấy luôn làm tôi cười."}]', '[{"phrase":"work for a company"},{"phrase":"a large company"},{"phrase":"start a company"},{"phrase":"keep someone company"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-02', 11, 'show', 'cho xem; chỉ (cho); cho thấy', 'verb', '[{"en":"She showed us photos from her trip to Japan.","vi":"Cô ấy cho chúng tôi xem ảnh chuyến đi Nhật Bản."},{"en":"Can you show me how to use this machine?","vi":"Bạn chỉ tôi cách dùng cái máy này được không?"},{"en":"The results show that more people are working from home.","vi":"Kết quả cho thấy có nhiều người làm việc tại nhà hơn."}]', '[{"phrase":"show someone how to"},{"phrase":"show someone around"},{"phrase":"results show"}]', 'show – showed – shown');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-02', 12, 'life', 'cuộc sống; cuộc đời; sự sống', 'noun', '[{"en":"Life in the city is busy and expensive.","vi":"Cuộc sống ở thành phố bận rộn và đắt đỏ."},{"en":"He spent his whole life in this small village.","vi":"Ông ấy sống cả đời ở ngôi làng nhỏ này."},{"en":"Scientists are still looking for life on other planets.","vi":"Các nhà khoa học vẫn đang tìm kiếm sự sống trên các hành tinh khác."}]', '[{"phrase":"daily life"},{"phrase":"real life"},{"phrase":"your whole life"},{"phrase":"save someone''s life"}]', 'số nhiều: lives');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-02', 13, 'man', 'người đàn ông; đàn ông, nam giới', 'noun', '[{"en":"A man in a blue jacket asked me for directions.","vi":"Một người đàn ông mặc áo khoác xanh hỏi đường tôi."},{"en":"The old man lives alone with his cat.","vi":"Ông cụ sống một mình với con mèo."},{"en":"Both men and women can apply for this job.","vi":"Cả nam và nữ đều có thể ứng tuyển công việc này."}]', '[{"phrase":"a young man"},{"phrase":"an old man"},{"phrase":"a married man"},{"phrase":"men and women"}]', 'số nhiều: men');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-02', 14, 'change', 'thay đổi; đổi, thay', 'verb', '[{"en":"You haven''t changed at all since high school.","vi":"Bạn chẳng thay đổi gì cả kể từ hồi cấp ba."},{"en":"We changed trains twice on the way to the coast.","vi":"Chúng tôi đã đổi tàu hai lần trên đường ra biển."},{"en":"Let me change my clothes before we go out.","vi":"Để tôi thay quần áo trước khi chúng ta ra ngoài."}]', '[{"phrase":"change your mind"},{"phrase":"change clothes"},{"phrase":"change trains"},{"phrase":"change the subject"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-02', 15, 'place', 'nơi, chỗ; nhà (của ai); vị trí', 'noun', '[{"en":"This is a great place to have lunch.","vi":"Đây là một chỗ ăn trưa rất tuyệt."},{"en":"Let''s meet at my place after work.","vi":"Tan làm mình gặp nhau ở nhà tôi nhé."},{"en":"She finished in second place in the race.","vi":"Cô ấy về đích ở vị trí thứ hai trong cuộc đua."}]', '[{"phrase":"take place"},{"phrase":"a great place to"},{"phrase":"first place"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-02', 16, 'long', 'dài; lâu', 'adjective', '[{"en":"My sister has long black hair like our mother.","vi":"Chị tôi có mái tóc đen dài giống mẹ."},{"en":"It was a long day, so I went to bed early.","vi":"Hôm đó là một ngày dài nên tôi đi ngủ sớm."},{"en":"How long does it take to get to the airport?","vi":"Đi đến sân bay mất bao lâu?"}]', '[{"phrase":"a long time"},{"phrase":"long hair"},{"phrase":"a long way"},{"phrase":"a long day"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-02', 17, 'between', 'giữa, ở giữa', 'preposition', '[{"en":"The bank is between the post office and the school.","vi":"Ngân hàng nằm giữa bưu điện và trường học."},{"en":"I usually have a snack between lunch and dinner.","vi":"Tôi thường ăn vặt giữa bữa trưa và bữa tối."},{"en":"What''s the difference between these two phones?","vi":"Hai chiếc điện thoại này khác nhau ở điểm nào?"}]', '[{"phrase":"the difference between"},{"phrase":"in between"},{"phrase":"between A and B"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-02', 18, 'feel', 'cảm thấy; sờ thấy, có cảm giác', 'verb', '[{"en":"I feel tired after a long day at work.","vi":"Tôi thấy mệt sau một ngày dài làm việc."},{"en":"How do you feel about moving to a new city?","vi":"Bạn cảm thấy thế nào về việc chuyển đến một thành phố mới?"},{"en":"The baby''s skin felt soft and warm.","vi":"Da em bé sờ vào thấy mềm và ấm."}]', '[{"phrase":"feel tired"},{"phrase":"feel better"},{"phrase":"feel sorry for"},{"phrase":"feel like"}]', 'feel – felt – felt');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-02', 19, 'still', 'vẫn, vẫn còn', 'adverb', '[{"en":"Are you still living in the same apartment?","vi":"Bạn vẫn sống ở căn hộ cũ à?"},{"en":"It''s almost noon, and he is still asleep.","vi":"Gần trưa rồi mà anh ấy vẫn còn ngủ."},{"en":"I studied hard, but I still failed the test.","vi":"Tôi đã học chăm chỉ nhưng vẫn trượt bài kiểm tra."}]', '[{"phrase":"still waiting"},{"phrase":"still alive"},{"phrase":"still asleep"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-02', 20, 'problem', 'vấn đề; rắc rối, trục trặc', 'noun', '[{"en":"We''re having a problem with the kitchen sink again.","vi":"Bồn rửa trong bếp nhà chúng tôi lại bị trục trặc."},{"en":"Talking to a friend can help you solve a problem.","vi":"Trò chuyện với bạn bè có thể giúp bạn giải quyết vấn đề."},{"en":"No problem, I can pick you up from the station.","vi":"Không sao, tôi có thể đón bạn ở nhà ga."}]', '[{"phrase":"solve a problem"},{"phrase":"have a problem with"},{"phrase":"no problem"},{"phrase":"a serious problem"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-02', 21, 'write', 'viết', 'verb', '[{"en":"Please write your name at the top of the page.","vi":"Hãy viết tên của bạn ở đầu trang."},{"en":"She wrote a long letter to her grandparents.","vi":"Cô ấy đã viết một lá thư dài cho ông bà."},{"en":"I have to write a report for my boss by Friday.","vi":"Tôi phải viết báo cáo cho sếp trước thứ Sáu."}]', '[{"phrase":"write a letter"},{"phrase":"write a report"},{"phrase":"write down"},{"phrase":"write an email"}]', 'write – wrote – written');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-02', 22, 'same', 'giống nhau, như nhau; cùng', 'adjective', '[{"en":"We were born in the same year.","vi":"Chúng tôi sinh cùng một năm."},{"en":"Your bag looks the same as mine.","vi":"Túi của bạn trông giống hệt túi của tôi."},{"en":"He orders the same thing every time we eat here.","vi":"Lần nào ăn ở đây anh ấy cũng gọi đúng một món đó."}]', '[{"phrase":"the same as"},{"phrase":"at the same time"},{"phrase":"the same thing"},{"phrase":"exactly the same"}]', 'thường đi với the: the same');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-02', 23, 'lot', 'nhiều, rất nhiều', 'noun', '[{"en":"There were a lot of people at the market today.","vi":"Hôm nay ở chợ có rất đông người."},{"en":"Thanks a lot for helping me move.","vi":"Cảm ơn bạn nhiều vì đã giúp tôi chuyển nhà."},{"en":"She has changed a lot since last year.","vi":"Cô ấy đã thay đổi nhiều kể từ năm ngoái."}]', '[{"phrase":"a lot of"},{"phrase":"lots of"},{"phrase":"thanks a lot"},{"phrase":"quite a lot"}]', 'thường dùng: a lot of / lots of + danh từ');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-02', 24, 'great', 'tuyệt vời; lớn, to lớn', 'adjective', '[{"en":"We had a great time at the beach.","vi":"Chúng tôi đã có khoảng thời gian tuyệt vời ở biển."},{"en":"Your new apartment looks great with all those plants.","vi":"Căn hộ mới của bạn trông thật tuyệt với mấy chậu cây đó."},{"en":"Our first charity event was a great success.","vi":"Sự kiện từ thiện đầu tiên của chúng tôi đã thành công lớn."}]', '[{"phrase":"a great time"},{"phrase":"a great idea"},{"phrase":"a great deal"},{"phrase":"a great success"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-02', 25, 'try', 'cố gắng; thử', 'verb', '[{"en":"I''ll try to finish the report by tonight.","vi":"Tôi sẽ cố gắng hoàn thành báo cáo trước tối nay."},{"en":"Have you ever tried Vietnamese iced coffee?","vi":"Bạn đã bao giờ thử cà phê đá Việt Nam chưa?"},{"en":"Can I try on these shoes in a smaller size?","vi":"Tôi có thể thử đôi giày này cỡ nhỏ hơn không?"}]', '[{"phrase":"try to do something"},{"phrase":"try hard"},{"phrase":"try on"},{"phrase":"try your best"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-02', 26, 'leave', 'rời đi, rời khỏi; để lại, bỏ quên', 'verb', '[{"en":"What time does your train leave in the morning?","vi":"Buổi sáng tàu của bạn khởi hành lúc mấy giờ?"},{"en":"She leaves home at seven every morning.","vi":"Sáng nào cô ấy cũng ra khỏi nhà lúc bảy giờ."},{"en":"I left my umbrella on the bus.","vi":"Tôi để quên ô trên xe buýt."}]', '[{"phrase":"leave home"},{"phrase":"leave a message"},{"phrase":"leave school"},{"phrase":"leave for work"}]', 'leave – left – left');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-02', 27, 'number', 'số; số lượng', 'noun', '[{"en":"Could you give me your phone number, please?","vi":"Bạn cho tôi xin số điện thoại được không?"},{"en":"The number of students in our class has grown.","vi":"Số lượng học sinh trong lớp chúng tôi đã tăng lên."},{"en":"A large number of tourists visit the old town every summer.","vi":"Mỗi mùa hè có rất nhiều du khách đến thăm phố cổ."}]', '[{"phrase":"phone number"},{"phrase":"the number of"},{"phrase":"a large number of"},{"phrase":"room number"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-02', 28, 'part', 'phần; bộ phận; vai (diễn)', 'noun', '[{"en":"The best part of the trip was the food.","vi":"Phần tuyệt nhất của chuyến đi là đồ ăn."},{"en":"My car needs a new part, so it''s at the garage.","vi":"Xe tôi cần thay một bộ phận mới nên đang nằm ở gara."},{"en":"She got a small part in the school play.","vi":"Cô ấy được nhận một vai nhỏ trong vở kịch của trường."}]', '[{"phrase":"take part in"},{"phrase":"an important part of"},{"phrase":"the best part"},{"phrase":"play a part"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-02', 29, 'point', 'điểm; ý, luận điểm; mục đích, ý nghĩa', 'noun', '[{"en":"Our team won the game by two points.","vi":"Đội của chúng tôi thắng trận với cách biệt hai điểm."},{"en":"You make a good point about the cost of the trip.","vi":"Bạn đã nêu ra một ý hay về chi phí của chuyến đi."},{"en":"What''s the point of buying a car if you never drive?","vi":"Mua ô tô thì có ích gì nếu bạn chẳng bao giờ lái?"}]', '[{"phrase":"make a good point"},{"phrase":"what''s the point"},{"phrase":"at some point"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('ngsl-1-02', 30, 'little', 'nhỏ, bé; ít, một chút', 'adjective', '[{"en":"We live in a little house near the river.","vi":"Chúng tôi sống trong một ngôi nhà nhỏ gần sông."},{"en":"My little sister is starting school this year.","vi":"Em gái tôi năm nay bắt đầu đi học."},{"en":"Could you speak a little more slowly, please?","vi":"Bạn nói chậm hơn một chút được không?"}]', '[{"phrase":"a little bit"},{"phrase":"a little more"},{"phrase":"little by little"}]', 'a little = một ít; little = rất ít (gần như không)');

-- awl-1-01: Học thuật Sublist 1 · Bộ 1 (30 từ)
INSERT INTO preset_decks (code, level_code, name, description, color, icon, position) VALUES ('awl-1-01', 'awl-1', 'Học thuật Sublist 1 · Bộ 1', 'Academic Word List, sublist 1', '#a974ff', 'GraduationCap', 1);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-01', 1, 'analyse', 'phân tích', 'verb', '[{"en":"Researchers analysed data from more than two thousand patients.","vi":"Các nhà nghiên cứu đã phân tích dữ liệu từ hơn hai nghìn bệnh nhân."},{"en":"Before writing the report, we need to analyse the survey results carefully.","vi":"Trước khi viết báo cáo, chúng ta cần phân tích kỹ kết quả khảo sát."},{"en":"The team is still analysing why sales fell last quarter.","vi":"Nhóm vẫn đang phân tích lý do doanh số giảm trong quý trước."}]', '[{"phrase":"analyse data"},{"phrase":"analyse results"},{"phrase":"carefully analyse"}]', 'Anh: analyse · Mỹ: analyze');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-01', 2, 'approach', 'cách tiếp cận; phương pháp', 'noun', '[{"en":"The school has taken a new approach to teaching reading.","vi":"Nhà trường đã áp dụng một cách tiếp cận mới trong việc dạy đọc."},{"en":"This approach works well for small businesses but not for large ones.","vi":"Phương pháp này hiệu quả với doanh nghiệp nhỏ nhưng không hiệu quả với doanh nghiệp lớn."},{"en":"Scientists are testing a different approach to treating the disease.","vi":"Các nhà khoa học đang thử nghiệm một phương pháp khác để điều trị căn bệnh này."}]', '[{"phrase":"take an approach"},{"phrase":"a new approach"},{"phrase":"different approach"},{"phrase":"approach to"}]', 'approach to + danh từ / V-ing');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-01', 3, 'area', 'khu vực; lĩnh vực; diện tích', 'noun', '[{"en":"Many families have moved out of the city into rural areas.","vi":"Nhiều gia đình đã rời thành phố để chuyển về các vùng nông thôn."},{"en":"Her main area of research is language development in children.","vi":"Lĩnh vực nghiên cứu chính của cô ấy là sự phát triển ngôn ngữ ở trẻ em."},{"en":"The park covers an area of about fifty square kilometers.","vi":"Công viên có diện tích khoảng năm mươi ki-lô-mét vuông."}]', '[{"phrase":"rural area"},{"phrase":"urban area"},{"phrase":"area of research"},{"phrase":"cover an area"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-01', 4, 'assess', 'đánh giá', 'verb', '[{"en":"Teachers assess students'' progress at the end of each term.","vi":"Giáo viên đánh giá sự tiến bộ của học sinh vào cuối mỗi học kỳ."},{"en":"It is too early to assess the impact of the new policy.","vi":"Còn quá sớm để đánh giá tác động của chính sách mới."},{"en":"Experts were called in to assess the damage after the flood.","vi":"Các chuyên gia được mời đến để đánh giá thiệt hại sau trận lũ."}]', '[{"phrase":"assess the impact"},{"phrase":"assess the damage"},{"phrase":"assess progress"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-01', 5, 'assume', 'cho rằng; giả định; đảm nhận', 'verb', '[{"en":"Many people assume that older workers cannot learn new skills.","vi":"Nhiều người cho rằng người lao động lớn tuổi không thể học kỹ năng mới."},{"en":"For this calculation, we assume that prices will stay the same.","vi":"Trong phép tính này, chúng tôi giả định rằng giá cả sẽ giữ nguyên."},{"en":"She will assume responsibility for the project next month.","vi":"Tháng sau cô ấy sẽ đảm nhận trách nhiệm về dự án."}]', '[{"phrase":"reasonable to assume"},{"phrase":"widely assumed"},{"phrase":"assume responsibility"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-01', 6, 'authority', 'chính quyền; thẩm quyền; chuyên gia', 'noun', '[{"en":"Local authorities have closed the road for repairs.","vi":"Chính quyền địa phương đã đóng con đường để sửa chữa."},{"en":"Only the manager has the authority to approve payments.","vi":"Chỉ người quản lý mới có thẩm quyền phê duyệt các khoản thanh toán."},{"en":"She is a leading authority on climate change.","vi":"Bà ấy là một chuyên gia hàng đầu về biến đổi khí hậu."}]', '[{"phrase":"local authorities"},{"phrase":"have the authority to"},{"phrase":"an authority on"},{"phrase":"health authorities"}]', 'the authorities: nhà chức trách');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-01', 7, 'available', 'có sẵn; rảnh', 'adjective', '[{"en":"The full report is publicly available on the company website.","vi":"Bản báo cáo đầy đủ được công khai trên trang web của công ty."},{"en":"Free parking is available for all visitors.","vi":"Có chỗ đỗ xe miễn phí cho tất cả khách đến thăm."},{"en":"Is the manager available for a meeting this afternoon?","vi":"Chiều nay người quản lý có rảnh để họp không?"}]', '[{"phrase":"readily available"},{"phrase":"widely available"},{"phrase":"publicly available"},{"phrase":"available for"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-01', 8, 'benefit', 'lợi ích; trợ cấp', 'noun', '[{"en":"Regular exercise has many benefits for mental health.","vi":"Tập thể dục thường xuyên có nhiều lợi ích cho sức khỏe tinh thần."},{"en":"The new system will bring clear benefits to small farmers.","vi":"Hệ thống mới sẽ mang lại lợi ích rõ rệt cho các nông hộ nhỏ."},{"en":"People who lose their jobs may apply for unemployment benefits.","vi":"Những người mất việc có thể nộp đơn xin trợ cấp thất nghiệp."}]', '[{"phrase":"health benefits"},{"phrase":"economic benefits"},{"phrase":"unemployment benefits"}]', 'Cũng là động từ: benefit from (được hưởng lợi từ)');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-01', 9, 'concept', 'khái niệm; ý tưởng', 'noun', '[{"en":"Young children find the concept of time difficult to understand.","vi":"Trẻ nhỏ thấy khái niệm thời gian rất khó hiểu."},{"en":"This chapter introduces the basic concepts of economics.","vi":"Chương này giới thiệu các khái niệm cơ bản của kinh tế học."},{"en":"The designers came up with a fresh concept for the new store.","vi":"Các nhà thiết kế đã nghĩ ra một ý tưởng mới mẻ cho cửa hàng mới."}]', '[{"phrase":"basic concept"},{"phrase":"key concept"},{"phrase":"concept of"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-01', 10, 'consist', 'gồm có, bao gồm', 'verb', '[{"en":"The committee consists of twelve members from different departments.","vi":"Ủy ban gồm mười hai thành viên đến từ các phòng ban khác nhau."},{"en":"The course consists of ten lectures and three written assignments.","vi":"Khóa học gồm mười bài giảng và ba bài tập viết."},{"en":"Their diet consisted mainly of fish and rice.","vi":"Chế độ ăn của họ chủ yếu gồm cá và cơm."}]', '[{"phrase":"consist of"},{"phrase":"consist mainly of"},{"phrase":"consist entirely of"}]', 'consist of + danh từ; không dùng ở thể bị động');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-01', 11, 'constitute', 'cấu thành, tạo thành; chiếm; được coi là', 'verb', '[{"en":"Women constitute nearly half of the country''s workforce.","vi":"Phụ nữ chiếm gần một nửa lực lượng lao động của cả nước."},{"en":"Such behavior may constitute a serious threat to public safety.","vi":"Hành vi như vậy có thể được coi là mối đe dọa nghiêm trọng đối với an toàn công cộng."},{"en":"These ten principles constitute the basis of the new law.","vi":"Mười nguyên tắc này tạo thành nền tảng của bộ luật mới."}]', '[{"phrase":"constitute a threat"},{"phrase":"constitute a large proportion"},{"phrase":"constitute a breach"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-01', 12, 'context', 'bối cảnh; ngữ cảnh', 'noun', '[{"en":"These events must be understood in their historical context.","vi":"Những sự kiện này phải được hiểu trong bối cảnh lịch sử của chúng."},{"en":"You can often guess the meaning of a word from the context.","vi":"Bạn thường có thể đoán nghĩa của một từ dựa vào ngữ cảnh."},{"en":"The writer complained that her comments had been taken out of context.","vi":"Nhà văn phàn nàn rằng những nhận xét của bà đã bị trích dẫn tách khỏi ngữ cảnh."}]', '[{"phrase":"historical context"},{"phrase":"social context"},{"phrase":"in this context"},{"phrase":"out of context"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-01', 13, 'contract', 'hợp đồng', 'noun', '[{"en":"Both companies signed a three-year contract last week.","vi":"Tuần trước, hai công ty đã ký một hợp đồng ba năm."},{"en":"Many young people now work on short-term contracts.","vi":"Nhiều người trẻ hiện nay làm việc theo hợp đồng ngắn hạn."},{"en":"If the supplier breaks the contract, we can ask for our money back.","vi":"Nếu nhà cung cấp vi phạm hợp đồng, chúng ta có thể yêu cầu hoàn tiền."}]', '[{"phrase":"sign a contract"},{"phrase":"break a contract"},{"phrase":"short-term contract"},{"phrase":"renew a contract"}]', 'Động từ contract (nhấn âm 2): co lại');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-01', 14, 'create', 'tạo ra; gây ra', 'verb', '[{"en":"The new factory will create around five hundred jobs.","vi":"Nhà máy mới sẽ tạo ra khoảng năm trăm việc làm."},{"en":"The students created a short video about saving water.","vi":"Các sinh viên đã tạo một video ngắn về việc tiết kiệm nước."},{"en":"Poor planning can create serious problems later on.","vi":"Lập kế hoạch kém có thể gây ra những vấn đề nghiêm trọng về sau."}]', '[{"phrase":"create jobs"},{"phrase":"create opportunities"},{"phrase":"create problems"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-01', 15, 'data', 'dữ liệu; số liệu', 'noun', '[{"en":"The data show a clear link between sleep and memory.","vi":"Dữ liệu cho thấy mối liên hệ rõ ràng giữa giấc ngủ và trí nhớ."},{"en":"We collected data from over three hundred schools.","vi":"Chúng tôi đã thu thập dữ liệu từ hơn ba trăm trường học."},{"en":"The latest data on household spending will be published next week.","vi":"Số liệu mới nhất về chi tiêu hộ gia đình sẽ được công bố vào tuần tới."}]', '[{"phrase":"collect data"},{"phrase":"data analysis"},{"phrase":"reliable data"},{"phrase":"the latest data"}]', 'Số nhiều của datum; đi được với động từ số ít hoặc số nhiều');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-01', 16, 'define', 'định nghĩa; xác định', 'verb', '[{"en":"It is hard to define exactly what makes a good teacher.","vi":"Rất khó để định nghĩa chính xác thế nào là một giáo viên giỏi."},{"en":"In this study, poverty is defined as living on less than two dollars a day.","vi":"Trong nghiên cứu này, nghèo đói được định nghĩa là sống với dưới hai đô la mỗi ngày."},{"en":"The contract clearly defines the duties of each partner.","vi":"Hợp đồng xác định rõ nghĩa vụ của mỗi bên."}]', '[{"phrase":"clearly define"},{"phrase":"be defined as"},{"phrase":"broadly defined"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-01', 17, 'derive', 'bắt nguồn (từ); có được, rút ra (từ)', 'verb', '[{"en":"Many English words are derived from Latin or Greek.","vi":"Nhiều từ tiếng Anh có nguồn gốc từ tiếng La-tinh hoặc tiếng Hy Lạp."},{"en":"The results were derived from a survey of 500 teachers.","vi":"Các kết quả này được rút ra từ một cuộc khảo sát 500 giáo viên."},{"en":"Older people often derive great pleasure from gardening.","vi":"Người lớn tuổi thường tìm thấy niềm vui lớn từ việc làm vườn."}]', '[{"phrase":"derive from"},{"phrase":"be derived from"},{"phrase":"derive pleasure from"}]', 'derive from: bắt nguồn từ; derive sth from sth: có được cái gì từ');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-01', 18, 'distribute', 'phân phối; phân phát; phân bổ', 'verb', '[{"en":"Volunteers distributed food and water to families after the storm.","vi":"Các tình nguyện viên đã phát thực phẩm và nước cho các gia đình sau cơn bão."},{"en":"The company distributes its products to over forty countries.","vi":"Công ty phân phối sản phẩm của mình tới hơn bốn mươi quốc gia."},{"en":"Wealth is not evenly distributed across the population.","vi":"Của cải không được phân bổ đồng đều trong dân cư."}]', '[{"phrase":"distribute food"},{"phrase":"evenly distributed"},{"phrase":"widely distributed"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-01', 19, 'economy', 'nền kinh tế', 'noun', '[{"en":"The global economy grew more slowly than expected last year.","vi":"Năm ngoái, nền kinh tế toàn cầu tăng trưởng chậm hơn dự kiến."},{"en":"Tourism plays an important role in the local economy.","vi":"Du lịch đóng vai trò quan trọng trong nền kinh tế địa phương."},{"en":"Experts believe the economy will recover by next spring.","vi":"Các chuyên gia tin rằng nền kinh tế sẽ phục hồi vào mùa xuân tới."}]', '[{"phrase":"global economy"},{"phrase":"local economy"},{"phrase":"boost the economy"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-01', 20, 'environment', 'môi trường; hoàn cảnh', 'noun', '[{"en":"Plastic waste is causing serious damage to the environment.","vi":"Rác thải nhựa đang gây thiệt hại nghiêm trọng cho môi trường."},{"en":"Children learn best in a safe and friendly environment.","vi":"Trẻ em học tốt nhất trong một môi trường an toàn và thân thiện."},{"en":"Staff say the company offers a pleasant working environment.","vi":"Nhân viên cho biết công ty có môi trường làm việc dễ chịu."}]', '[{"phrase":"protect the environment"},{"phrase":"natural environment"},{"phrase":"working environment"},{"phrase":"learning environment"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-01', 21, 'establish', 'thành lập; thiết lập; xác định', 'verb', '[{"en":"The research center was established in 1998 to study ocean pollution.","vi":"Trung tâm nghiên cứu được thành lập năm 1998 để nghiên cứu ô nhiễm đại dương."},{"en":"The two countries established trade links in the early 1990s.","vi":"Hai nước đã thiết lập quan hệ thương mại vào đầu những năm 1990."},{"en":"Police are trying to establish the cause of the fire.","vi":"Cảnh sát đang cố gắng xác định nguyên nhân vụ cháy."}]', '[{"phrase":"establish a relationship"},{"phrase":"establish links"},{"phrase":"establish the cause"},{"phrase":"well established"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-01', 22, 'estimate', 'ước tính', 'verb', '[{"en":"Experts estimate that the project will cost two million dollars.","vi":"Các chuyên gia ước tính dự án sẽ tốn hai triệu đô la."},{"en":"It is difficult to estimate how many people use the service.","vi":"Rất khó ước tính có bao nhiêu người sử dụng dịch vụ này."},{"en":"The city''s population is estimated at around 1.5 million.","vi":"Dân số của thành phố ước tính vào khoảng 1,5 triệu người."}]', '[{"phrase":"estimate the cost"},{"phrase":"be estimated at"},{"phrase":"it is estimated that"}]', 'Cũng là danh từ: a rough estimate (ước tính sơ bộ)');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-01', 23, 'evident', 'rõ ràng, hiển nhiên', 'adjective', '[{"en":"It was evident that the students had not read the article.","vi":"Rõ ràng là các sinh viên đã không đọc bài báo đó."},{"en":"The effects of climate change are already evident in many regions.","vi":"Tác động của biến đổi khí hậu đã hiện rõ ở nhiều khu vực."},{"en":"Her love of science was evident from an early age.","vi":"Niềm yêu thích khoa học của cô ấy đã thể hiện rõ từ khi còn nhỏ."}]', '[{"phrase":"it is evident that"},{"phrase":"clearly evident"},{"phrase":"become evident"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-01', 24, 'export', 'hàng xuất khẩu; sự xuất khẩu', 'noun', '[{"en":"Coffee is one of the country''s main exports.","vi":"Cà phê là một trong những mặt hàng xuất khẩu chính của đất nước."},{"en":"Rice exports rose by ten percent last year.","vi":"Năm ngoái, xuất khẩu gạo tăng mười phần trăm."},{"en":"The factory produces furniture mainly for export.","vi":"Nhà máy sản xuất đồ nội thất chủ yếu để xuất khẩu."}]', '[{"phrase":"main export"},{"phrase":"export market"},{"phrase":"for export"}]', 'Động từ export (nhấn âm 2): xuất khẩu');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-01', 25, 'factor', 'yếu tố, nhân tố', 'noun', '[{"en":"Cost is an important factor when choosing a university.","vi":"Chi phí là một yếu tố quan trọng khi chọn trường đại học."},{"en":"Several factors led to the fall in sales.","vi":"Một số yếu tố đã dẫn đến sự sụt giảm doanh số."},{"en":"Smoking is a major risk factor for heart disease.","vi":"Hút thuốc là một yếu tố nguy cơ chính gây bệnh tim."}]', '[{"phrase":"important factor"},{"phrase":"key factor"},{"phrase":"major factor"},{"phrase":"risk factor"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-01', 26, 'finance', 'tài chính', 'noun', '[{"en":"She has a degree in finance from a leading business school.","vi":"Cô ấy có bằng tài chính của một trường kinh doanh hàng đầu."},{"en":"Many students struggle to manage their personal finances.","vi":"Nhiều sinh viên gặp khó khăn trong việc quản lý tài chính cá nhân."},{"en":"The finance department will review the budget next week.","vi":"Phòng tài chính sẽ xem xét ngân sách vào tuần tới."}]', '[{"phrase":"personal finances"},{"phrase":"finance department"},{"phrase":"public finances"}]', 'Cũng là động từ: cấp vốn, tài trợ');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-01', 27, 'formula', 'công thức', 'noun', '[{"en":"Students must learn the formula for the area of a circle.","vi":"Học sinh phải học công thức tính diện tích hình tròn."},{"en":"The chemical formula for water is H2O.","vi":"Công thức hóa học của nước là H2O."},{"en":"There is no simple formula for success in business.","vi":"Không có công thức đơn giản nào để thành công trong kinh doanh."}]', '[{"phrase":"mathematical formula"},{"phrase":"chemical formula"},{"phrase":"simple formula"},{"phrase":"formula for"}]', 'Số nhiều: formulas hoặc formulae');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-01', 28, 'function', 'chức năng; hàm số', 'noun', '[{"en":"The main function of the heart is to pump blood around the body.","vi":"Chức năng chính của tim là bơm máu đi khắp cơ thể."},{"en":"This app has a very useful search function.","vi":"Ứng dụng này có chức năng tìm kiếm rất hữu ích."},{"en":"In this lesson, we will learn how to draw the graph of a function.","vi":"Trong bài học này, chúng ta sẽ học cách vẽ đồ thị của một hàm số."}]', '[{"phrase":"main function"},{"phrase":"perform a function"},{"phrase":"brain function"}]', 'Cũng là động từ: hoạt động; function as: đóng vai trò là');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-01', 29, 'identify', 'xác định; nhận ra, nhận diện', 'verb', '[{"en":"The study identified three main causes of stress at work.","vi":"Nghiên cứu đã xác định ba nguyên nhân chính gây căng thẳng tại nơi làm việc."},{"en":"Can you identify the bird in this picture?","vi":"Bạn có nhận diện được con chim trong bức ảnh này không?"},{"en":"Teachers need to identify students who need extra help early.","vi":"Giáo viên cần sớm nhận ra những học sinh cần được hỗ trợ thêm."}]', '[{"phrase":"identify the cause"},{"phrase":"identify problems"},{"phrase":"clearly identify"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-01', 30, 'income', 'thu nhập', 'noun', '[{"en":"Families with low incomes will receive extra support.","vi":"Các gia đình có thu nhập thấp sẽ được hỗ trợ thêm."},{"en":"Tourism is the island''s main source of income.","vi":"Du lịch là nguồn thu nhập chính của hòn đảo."},{"en":"Her monthly income increased after she changed jobs.","vi":"Thu nhập hàng tháng của cô ấy tăng lên sau khi cô chuyển việc."}]', '[{"phrase":"low income"},{"phrase":"source of income"},{"phrase":"household income"},{"phrase":"annual income"}]', NULL);

-- awl-1-02: Học thuật Sublist 1 · Bộ 2 (30 từ)
INSERT INTO preset_decks (code, level_code, name, description, color, icon, position) VALUES ('awl-1-02', 'awl-1', 'Học thuật Sublist 1 · Bộ 2', 'Academic Word List, sublist 1', '#a974ff', 'GraduationCap', 2);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-02', 1, 'indicate', 'cho thấy; chỉ ra; biểu thị', 'verb', '[{"en":"The results indicate a strong link between sleep and memory.","vi":"Kết quả cho thấy mối liên hệ chặt chẽ giữa giấc ngủ và trí nhớ."},{"en":"Recent surveys indicate that most employees prefer flexible working hours.","vi":"Các khảo sát gần đây chỉ ra rằng phần lớn nhân viên thích giờ làm việc linh hoạt."},{"en":"A red light on the panel indicates a problem with the power supply.","vi":"Đèn đỏ trên bảng điều khiển biểu thị sự cố về nguồn điện."}]', '[{"phrase":"results indicate"},{"phrase":"evidence indicates"},{"phrase":"clearly indicate"},{"phrase":"studies indicate"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-02', 2, 'individual', 'cá nhân; riêng; từng (người, cái)', 'adjective', '[{"en":"Teachers should pay attention to the individual needs of each student.","vi":"Giáo viên nên chú ý đến nhu cầu riêng của từng học sinh."},{"en":"The report looks at individual countries rather than the whole region.","vi":"Báo cáo xem xét từng quốc gia thay vì cả khu vực."},{"en":"The company rewards both team success and individual performance.","vi":"Công ty khen thưởng cả thành công của nhóm lẫn thành tích cá nhân."}]', '[{"phrase":"individual needs"},{"phrase":"individual performance"},{"phrase":"individual rights"},{"phrase":"individual responsibility"}]', 'Cũng là danh từ: an individual (một cá nhân)');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-02', 3, 'interpret', 'diễn giải; hiểu (là); phiên dịch', 'verb', '[{"en":"Researchers must be careful when they interpret results from small samples.","vi":"Các nhà nghiên cứu phải cẩn trọng khi diễn giải kết quả từ các mẫu nhỏ."},{"en":"His silence was interpreted as agreement by the rest of the team.","vi":"Sự im lặng của anh ấy được những người còn lại trong nhóm hiểu là đồng ý."},{"en":"She interpreted for the visiting engineers during the factory tour.","vi":"Cô ấy phiên dịch cho các kỹ sư đến thăm trong chuyến tham quan nhà máy."}]', '[{"phrase":"interpret data"},{"phrase":"interpret results"},{"phrase":"interpret something as"},{"phrase":"correctly interpret"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-02', 4, 'involve', 'bao gồm; đòi hỏi; cho tham gia', 'verb', '[{"en":"The job involves a lot of travel within the region.","vi":"Công việc này đòi hỏi phải đi lại nhiều trong khu vực."},{"en":"The study involved more than two thousand adults from five countries.","vi":"Nghiên cứu có sự tham gia của hơn hai nghìn người trưởng thành từ năm quốc gia."},{"en":"Parents should be involved in decisions about their children''s education.","vi":"Cha mẹ nên được tham gia vào các quyết định về việc học của con cái."}]', '[{"phrase":"be involved in"},{"phrase":"involve risk"},{"phrase":"directly involved"},{"phrase":"actively involve"}]', 'be involved in: tham gia vào, liên quan đến');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-02', 5, 'issue', 'vấn đề; số (báo, tạp chí)', 'noun', '[{"en":"Climate change is a major issue for coastal cities.","vi":"Biến đổi khí hậu là một vấn đề lớn đối với các thành phố ven biển."},{"en":"The committee will discuss the issue at its next meeting.","vi":"Ủy ban sẽ thảo luận vấn đề này tại cuộc họp tới."},{"en":"The article appeared in the latest issue of the journal.","vi":"Bài báo được đăng trong số mới nhất của tạp chí."}]', '[{"phrase":"major issue"},{"phrase":"discuss an issue"},{"phrase":"raise an issue"},{"phrase":"address an issue"}]', 'Cũng là động từ: issue a statement (ra tuyên bố)');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-02', 6, 'labour', 'lao động; nhân công', 'noun', '[{"en":"The factory moved production abroad to reduce labour costs.","vi":"Nhà máy chuyển hoạt động sản xuất ra nước ngoài để giảm chi phí nhân công."},{"en":"Many farms rely on seasonal labour during the harvest.","vi":"Nhiều trang trại dựa vào lao động thời vụ trong mùa thu hoạch."},{"en":"The labour market has become more competitive for young graduates.","vi":"Thị trường lao động đã trở nên cạnh tranh hơn đối với sinh viên mới tốt nghiệp."}]', '[{"phrase":"labour costs"},{"phrase":"labour market"},{"phrase":"skilled labour"},{"phrase":"cheap labour"}]', 'Anh: labour · Mỹ: labor; không đếm được');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-02', 7, 'legal', 'hợp pháp; (thuộc) pháp luật, pháp lý', 'adjective', '[{"en":"The company sought legal advice before signing the contract.","vi":"Công ty đã tìm tư vấn pháp lý trước khi ký hợp đồng."},{"en":"Is it legal to drive with a foreign license here?","vi":"Ở đây lái xe bằng giấy phép nước ngoài có hợp pháp không?"},{"en":"Every country has its own legal system and traditions.","vi":"Mỗi quốc gia đều có hệ thống pháp luật và truyền thống riêng."}]', '[{"phrase":"legal advice"},{"phrase":"legal system"},{"phrase":"legal action"},{"phrase":"legal requirement"}]', 'Trái nghĩa: illegal (bất hợp pháp)');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-02', 8, 'legislate', 'ban hành luật; lập pháp', 'verb', '[{"en":"Many governments have begun to legislate against plastic waste.","vi":"Nhiều chính phủ đã bắt đầu ban hành luật chống rác thải nhựa."},{"en":"It is difficult to legislate for every possible situation.","vi":"Thật khó để ban hành luật cho mọi tình huống có thể xảy ra."},{"en":"Several states have legislated to protect workers'' personal data.","vi":"Một số bang đã ban hành luật để bảo vệ dữ liệu cá nhân của người lao động."}]', '[{"phrase":"legislate against"},{"phrase":"legislate for"},{"phrase":"legislate to protect"}]', 'Danh từ: legislation (luật pháp; sự lập pháp)');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-02', 9, 'major', 'lớn; chính; quan trọng', 'adjective', '[{"en":"Traffic is a major cause of air pollution in large cities.","vi":"Giao thông là nguyên nhân chính gây ô nhiễm không khí ở các thành phố lớn."},{"en":"The new policy led to major changes in how staff are trained.","vi":"Chính sách mới đã dẫn đến những thay đổi lớn trong cách đào tạo nhân viên."},{"en":"Researchers faced a major problem when their funding was cut.","vi":"Các nhà nghiên cứu gặp phải một vấn đề lớn khi kinh phí bị cắt giảm."}]', '[{"phrase":"major cause"},{"phrase":"major change"},{"phrase":"major problem"},{"phrase":"major role"}]', 'Trái nghĩa: minor; (Mỹ, n) chuyên ngành chính ở đại học');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-02', 10, 'method', 'phương pháp; cách thức', 'noun', '[{"en":"This teaching method encourages students to work in small groups.","vi":"Phương pháp giảng dạy này khuyến khích học sinh làm việc theo nhóm nhỏ."},{"en":"Which method did you use to collect the data?","vi":"Bạn đã dùng phương pháp nào để thu thập dữ liệu?"},{"en":"Bank transfer is still the most common method of payment.","vi":"Chuyển khoản ngân hàng vẫn là phương thức thanh toán phổ biến nhất."}]', '[{"phrase":"teaching method"},{"phrase":"research method"},{"phrase":"method of payment"},{"phrase":"effective method"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-02', 11, 'occur', 'xảy ra; xuất hiện; nảy ra (trong đầu)', 'verb', '[{"en":"Most workplace accidents occur when safety rules are ignored.","vi":"Hầu hết tai nạn lao động xảy ra khi các quy định an toàn bị phớt lờ."},{"en":"The disease occurs mainly in tropical regions.","vi":"Căn bệnh này chủ yếu xuất hiện ở các vùng nhiệt đới."},{"en":"It never occurred to me that the data might be wrong.","vi":"Tôi chưa bao giờ nghĩ rằng dữ liệu có thể bị sai."}]', '[{"phrase":"occur naturally"},{"phrase":"frequently occur"},{"phrase":"occur to someone"}]', 'occur – occurred – occurring (gấp đôi r)');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-02', 12, 'percent', 'phần trăm', 'noun', '[{"en":"Sales rose by 15 percent in the first quarter.","vi":"Doanh số tăng 15 phần trăm trong quý đầu tiên."},{"en":"Only 40 percent of the students completed the online survey.","vi":"Chỉ 40 phần trăm sinh viên hoàn thành bản khảo sát trực tuyến."},{"en":"About 70 percent of the Earth''s surface is covered by water.","vi":"Khoảng 70 phần trăm bề mặt Trái Đất được bao phủ bởi nước."}]', '[{"phrase":"rise by 10 percent"},{"phrase":"percent of the population"},{"phrase":"a 5 percent increase"}]', 'Anh: per cent · Mỹ: percent; ký hiệu %');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-02', 13, 'period', 'giai đoạn; thời kỳ; khoảng thời gian', 'noun', '[{"en":"The project will be completed over a period of three years.","vi":"Dự án sẽ được hoàn thành trong khoảng thời gian ba năm."},{"en":"Prices remained fairly stable during this period of growth.","vi":"Giá cả vẫn khá ổn định trong suốt giai đoạn tăng trưởng này."},{"en":"New employees usually have a trial period of two months.","vi":"Nhân viên mới thường có thời gian thử việc hai tháng."}]', '[{"phrase":"over a period of"},{"phrase":"a period of time"},{"phrase":"trial period"},{"phrase":"short period"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-02', 14, 'policy', 'chính sách; quy định', 'noun', '[{"en":"The government introduced a new policy to support small businesses.","vi":"Chính phủ đã đưa ra một chính sách mới để hỗ trợ doanh nghiệp nhỏ."},{"en":"Our company has a strict policy on the use of personal phones.","vi":"Công ty chúng tôi có quy định nghiêm ngặt về việc sử dụng điện thoại cá nhân."},{"en":"Economic policy should focus on creating more stable jobs.","vi":"Chính sách kinh tế nên tập trung vào việc tạo ra nhiều việc làm ổn định hơn."}]', '[{"phrase":"introduce a policy"},{"phrase":"government policy"},{"phrase":"economic policy"},{"phrase":"policy on"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-02', 15, 'principle', 'nguyên tắc; nguyên lý', 'noun', '[{"en":"The course explains the basic principles of economics.","vi":"Khóa học giải thích những nguyên lý cơ bản của kinh tế học."},{"en":"Fairness is a key principle in our hiring process.","vi":"Công bằng là một nguyên tắc then chốt trong quy trình tuyển dụng của chúng tôi."},{"en":"In principle, the plan is good, but it may be too expensive.","vi":"Về nguyên tắc, kế hoạch này tốt, nhưng có thể quá tốn kém."}]', '[{"phrase":"basic principle"},{"phrase":"key principle"},{"phrase":"general principle"},{"phrase":"in principle"}]', 'principle (nguyên tắc) ≠ principal (hiệu trưởng; chính)');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-02', 16, 'proceed', 'tiếp tục; tiến hành; đi tới', 'verb', '[{"en":"After a short break, the meeting proceeded as planned.","vi":"Sau giờ nghỉ ngắn, cuộc họp tiếp tục như dự kiến."},{"en":"The city council decided to proceed with the new housing project.","vi":"Hội đồng thành phố quyết định tiến hành dự án nhà ở mới."},{"en":"Passengers on the morning flight should proceed to gate 12.","vi":"Hành khách của chuyến bay buổi sáng vui lòng đi đến cổng số 12."}]', '[{"phrase":"proceed with"},{"phrase":"proceed to"},{"phrase":"proceed as planned"}]', 'proceed with something: tiến hành việc gì');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-02', 17, 'process', 'quá trình; quy trình', 'noun', '[{"en":"Learning a language is a slow process that takes patience.","vi":"Học một ngôn ngữ là một quá trình chậm, cần sự kiên nhẫn."},{"en":"The company has simplified its application process for new customers.","vi":"Công ty đã đơn giản hóa quy trình đăng ký cho khách hàng mới."},{"en":"We are still in the process of reviewing your request.","vi":"Chúng tôi vẫn đang trong quá trình xem xét yêu cầu của bạn."}]', '[{"phrase":"in the process of"},{"phrase":"application process"},{"phrase":"decision-making process"},{"phrase":"production process"}]', 'Cũng là động từ: process data (xử lý dữ liệu)');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-02', 18, 'require', 'đòi hỏi; cần; yêu cầu', 'verb', '[{"en":"Most jobs in this field require a university degree.","vi":"Hầu hết công việc trong lĩnh vực này đòi hỏi bằng đại học."},{"en":"All visitors are required to sign in at reception.","vi":"Tất cả khách đến thăm đều được yêu cầu đăng ký tại quầy lễ tân."},{"en":"The experiment requires careful planning and accurate measurement.","vi":"Thí nghiệm này cần được lên kế hoạch cẩn thận và đo đạc chính xác."}]', '[{"phrase":"be required to"},{"phrase":"require careful planning"},{"phrase":"require attention"}]', 'be required to do something: được yêu cầu, bắt buộc phải làm gì');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-02', 19, 'research', 'nghiên cứu; sự nghiên cứu', 'noun', '[{"en":"Recent research shows that regular exercise can improve memory.","vi":"Nghiên cứu gần đây cho thấy tập thể dục thường xuyên có thể cải thiện trí nhớ."},{"en":"She is doing research on renewable energy at the university.","vi":"Cô ấy đang nghiên cứu về năng lượng tái tạo tại trường đại học."},{"en":"More research is needed before the drug can be approved.","vi":"Cần thêm nghiên cứu trước khi loại thuốc này được phê duyệt."}]', '[{"phrase":"do research"},{"phrase":"carry out research"},{"phrase":"research on"},{"phrase":"further research"}]', 'Không đếm được (không nói ''a research''); cũng là động từ');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-02', 20, 'respond', 'trả lời; phản hồi; phản ứng', 'verb', '[{"en":"The company responded quickly to customer complaints.","vi":"Công ty đã phản hồi nhanh chóng trước khiếu nại của khách hàng."},{"en":"Please respond to this email by Friday.","vi":"Vui lòng trả lời email này trước thứ Sáu."},{"en":"Patients usually respond well to this kind of treatment.","vi":"Bệnh nhân thường đáp ứng tốt với phương pháp điều trị này."}]', '[{"phrase":"respond to"},{"phrase":"respond quickly"},{"phrase":"respond well to"},{"phrase":"respond positively"}]', 'respond to something; danh từ: response');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-02', 21, 'role', 'vai trò; vai (diễn)', 'noun', '[{"en":"Technology plays an important role in modern healthcare.","vi":"Công nghệ đóng vai trò quan trọng trong ngành y tế hiện đại."},{"en":"Her role in the project is to manage the budget.","vi":"Vai trò của cô ấy trong dự án là quản lý ngân sách."},{"en":"He was offered the leading role in the school play.","vi":"Cậu ấy được mời đóng vai chính trong vở kịch của trường."}]', '[{"phrase":"play a role"},{"phrase":"important role"},{"phrase":"key role"},{"phrase":"leading role"}]', 'play a role in something: đóng vai trò trong việc gì');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-02', 22, 'section', 'phần; mục; khu (vực)', 'noun', '[{"en":"Please read the first section of the report before the meeting.","vi":"Vui lòng đọc phần đầu tiên của báo cáo trước cuộc họp."},{"en":"The test has three sections: reading, writing, and listening.","vi":"Bài kiểm tra có ba phần: đọc, viết và nghe."},{"en":"The fruit and vegetable section is at the back of the store.","vi":"Khu rau củ quả nằm ở phía sau cửa hàng."}]', '[{"phrase":"section of the report"},{"phrase":"the following section"},{"phrase":"the previous section"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-02', 23, 'sector', 'khu vực (kinh tế); lĩnh vực; ngành', 'noun', '[{"en":"The public sector employs nearly a quarter of the workforce.","vi":"Khu vực công sử dụng gần một phần tư lực lượng lao động."},{"en":"Jobs in the technology sector are growing quickly.","vi":"Việc làm trong lĩnh vực công nghệ đang tăng nhanh."},{"en":"Tourism is the largest sector of the local economy.","vi":"Du lịch là ngành lớn nhất của nền kinh tế địa phương."}]', '[{"phrase":"public sector"},{"phrase":"private sector"},{"phrase":"service sector"},{"phrase":"manufacturing sector"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-02', 24, 'significant', 'đáng kể; quan trọng; có ý nghĩa (thống kê)', 'adjective', '[{"en":"There has been a significant increase in online shopping.","vi":"Mua sắm trực tuyến đã có sự gia tăng đáng kể."},{"en":"The study found no significant difference between the two groups.","vi":"Nghiên cứu không tìm thấy khác biệt có ý nghĩa giữa hai nhóm."},{"en":"This was a significant moment in the history of medicine.","vi":"Đây là một thời khắc quan trọng trong lịch sử y học."}]', '[{"phrase":"significant increase"},{"phrase":"significant difference"},{"phrase":"statistically significant"},{"phrase":"significant role"}]', 'Danh từ: significance; trạng từ: significantly');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-02', 25, 'similar', 'tương tự; giống nhau', 'adjective', '[{"en":"The two reports reached similar conclusions about the causes of the problem.","vi":"Hai báo cáo đưa ra những kết luận tương tự nhau về nguyên nhân của vấn đề."},{"en":"My new job is similar to my old one.","vi":"Công việc mới của tôi giống với công việc cũ."},{"en":"Similar results were found in studies in other countries.","vi":"Các nghiên cứu ở những nước khác cho ra kết quả tương tự."}]', '[{"phrase":"similar to"},{"phrase":"very similar"},{"phrase":"similar results"},{"phrase":"remarkably similar"}]', 'similar to something: giống với cái gì');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-02', 26, 'source', 'nguồn; nguồn gốc', 'noun', '[{"en":"Fruit is a good source of vitamins and fiber.","vi":"Trái cây là một nguồn vitamin và chất xơ tốt."},{"en":"Always check your sources before you cite them in an essay.","vi":"Hãy luôn kiểm tra nguồn tài liệu trước khi trích dẫn chúng trong bài luận."},{"en":"Engineers are still trying to find the source of the leak.","vi":"Các kỹ sư vẫn đang cố tìm ra nguồn gốc của chỗ rò rỉ."}]', '[{"phrase":"a good source of"},{"phrase":"main source of income"},{"phrase":"reliable source"},{"phrase":"energy source"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-02', 27, 'specific', 'cụ thể; riêng; đặc thù', 'adjective', '[{"en":"Can you give me a specific example of the problem?","vi":"Bạn có thể cho tôi một ví dụ cụ thể về vấn đề này không?"},{"en":"The training is designed for the specific needs of nurses.","vi":"Khóa đào tạo được thiết kế cho nhu cầu đặc thù của điều dưỡng."},{"en":"These plants grow only under very specific conditions.","vi":"Những loài cây này chỉ phát triển trong những điều kiện rất riêng biệt."}]', '[{"phrase":"specific example"},{"phrase":"specific needs"},{"phrase":"specific to"},{"phrase":"specific conditions"}]', 'specific to something: đặc trưng cho, chỉ có ở');
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-02', 28, 'structure', 'cấu trúc; cơ cấu; kết cấu', 'noun', '[{"en":"The essay has a clear structure with an introduction and a conclusion.","vi":"Bài luận có cấu trúc rõ ràng với phần mở bài và phần kết luận."},{"en":"Scientists studied the structure of the cell in great detail.","vi":"Các nhà khoa học đã nghiên cứu rất chi tiết cấu trúc của tế bào."},{"en":"Last year, the company changed its management structure.","vi":"Năm ngoái, công ty đã thay đổi cơ cấu quản lý."}]', '[{"phrase":"clear structure"},{"phrase":"basic structure"},{"phrase":"management structure"},{"phrase":"social structure"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-02', 29, 'theory', 'lý thuyết; học thuyết; giả thuyết', 'noun', '[{"en":"Economic theory cannot always predict how people will behave.","vi":"Lý thuyết kinh tế không phải lúc nào cũng dự đoán được con người sẽ hành xử ra sao."},{"en":"The idea sounds good in theory, but it rarely works in practice.","vi":"Ý tưởng này nghe hay trên lý thuyết, nhưng hiếm khi hiệu quả trong thực tế."},{"en":"Scientists have developed a new theory to explain the data.","vi":"Các nhà khoa học đã xây dựng một lý thuyết mới để giải thích dữ liệu."}]', '[{"phrase":"in theory"},{"phrase":"develop a theory"},{"phrase":"economic theory"},{"phrase":"support a theory"}]', NULL);
INSERT INTO preset_deck_cards (deck_code, position, english, vietnamese, part_of_speech, examples, collocations, notes) VALUES ('awl-1-02', 30, 'vary', 'thay đổi; khác nhau; làm đa dạng', 'verb', '[{"en":"Hotel prices vary greatly depending on the time of year.","vi":"Giá khách sạn thay đổi rất nhiều tùy theo thời điểm trong năm."},{"en":"Opinions on the new policy varied widely among staff.","vi":"Ý kiến của nhân viên về chính sách mới rất khác nhau."},{"en":"Try to vary your diet by eating different kinds of vegetables.","vi":"Hãy cố gắng đa dạng hóa chế độ ăn bằng cách ăn nhiều loại rau khác nhau."}]', '[{"phrase":"vary greatly"},{"phrase":"vary widely"},{"phrase":"vary in size"},{"phrase":"vary depending on"}]', 'vary – varied – varies; tính từ: various, danh từ: variety');
